-- Generated by scripts/gen-puzzle-seed.mjs - do not edit by hand.
--
-- The daily puzzle's pool, as Postgres sees it. 160 players.
-- Regenerate and re-run this after every roster sync; see the script for
-- what goes wrong when the two copies drift.
--
-- Rows are never deleted, only re-flagged. Everything the sync has ever
-- seen keeps its place in the table - hard mode will want it back, and a
-- delete would break the foreign key from any daily_puzzles row that
-- already used that player.
--
-- So the pool is DECLARED rather than added to: every row is switched off
-- first and the 160 below switch themselves back on. Without that, a
-- player who drops out of the pool keeps whatever flags they had the last
-- time they were in it.
update public.puzzle_players set answerable = false, guessable = false;

insert into public.puzzle_players
  (espn_id, name, team, position, conference, division, answerable, guessable, height_in, weight_lb, age, jersey, college)
values
  ('8439', 'Aaron Rodgers', 'PIT', 'QB', 'AFC', 'North', true, true, 74, 223, 42, 8, 'California'),
  ('3052587', 'Baker Mayfield', 'TB', 'QB', 'NFC', 'South', true, true, 73, 215, 31, 6, 'Oklahoma'),
  ('4426338', 'Bo Nix', 'DEN', 'QB', 'AFC', 'West', true, true, 74, 217, 26, 10, 'Oregon'),
  ('4361741', 'Brock Purdy', 'SF', 'QB', 'NFC', 'West', true, true, 73, 220, 26, 13, 'Iowa State'),
  ('4685720', 'Bryce Young', 'CAR', 'QB', 'NFC', 'South', true, true, 70, 204, 25, 9, 'Alabama'),
  ('4432577', 'C.J. Stroud', 'HOU', 'QB', 'AFC', 'South', true, true, 75, 218, 24, 7, 'Ohio State'),
  ('4431611', 'Caleb Williams', 'CHI', 'QB', 'NFC', 'North', true, true, 73, 226, 24, 18, 'USC'),
  ('4688380', 'Cam Ward', 'TEN', 'QB', 'AFC', 'South', true, true, 74, 219, 24, 1, 'Miami'),
  ('2577417', 'Dak Prescott', 'DAL', 'QB', 'NFC', 'East', true, true, 74, 230, 33, 4, 'Mississippi State'),
  ('3917792', 'Daniel Jones', 'IND', 'QB', 'AFC', 'South', true, true, 77, 230, 29, 17, 'Duke'),
  ('3122840', 'Deshaun Watson', 'CLE', 'QB', 'AFC', 'North', true, true, 75, 223, 30, 4, 'Clemson'),
  ('4431452', 'Drake Maye', 'NE', 'QB', 'AFC', 'East', true, true, 76, 225, 23, 10, 'North Carolina'),
  ('15864', 'Geno Smith', 'NYJ', 'QB', 'AFC', 'East', true, true, 74, 221, 35, 7, 'West Virginia'),
  ('2578570', 'Jacoby Brissett', 'ARI', 'QB', 'NFC', 'West', true, true, 76, 235, 33, 7, 'NC State'),
  ('4040715', 'Jalen Hurts', 'PHI', 'QB', 'NFC', 'East', true, true, 73, 223, 28, 1, 'Oklahoma'),
  ('3046779', 'Jared Goff', 'DET', 'QB', 'NFC', 'North', true, true, 76, 217, 31, 16, 'California'),
  ('4689114', 'Jaxson Dart', 'NYG', 'QB', 'NFC', 'East', true, true, 74, 223, 23, 6, 'Ole Miss'),
  ('4426348', 'Jayden Daniels', 'WAS', 'QB', 'NFC', 'East', true, true, 76, 210, 25, 5, 'LSU'),
  ('3915511', 'Joe Burrow', 'CIN', 'QB', 'AFC', 'North', true, true, 76, 215, 29, 9, 'LSU'),
  ('4036378', 'Jordan Love', 'GB', 'QB', 'NFC', 'North', true, true, 76, 219, 27, 10, 'Utah State'),
  ('3918298', 'Josh Allen', 'BUF', 'QB', 'AFC', 'East', true, true, 77, 237, 30, 17, 'Wyoming'),
  ('4038941', 'Justin Herbert', 'LAC', 'QB', 'AFC', 'West', true, true, 78, 236, 28, 10, 'Oregon'),
  ('14880', 'Kirk Cousins', 'LV', 'QB', 'AFC', 'West', true, true, 75, 209, 38, 8, 'Michigan State'),
  ('3917315', 'Kyler Murray', 'MIN', 'QB', 'NFC', 'North', true, true, 70, 207, 29, 1, 'Oklahoma'),
  ('3916387', 'Lamar Jackson', 'BAL', 'QB', 'AFC', 'North', true, true, 74, 205, 29, 8, 'Louisville'),
  ('4242512', 'Malik Willis', 'MIA', 'QB', 'AFC', 'East', true, true, 73, 225, 27, 2, 'Liberty'),
  ('12483', 'Matthew Stafford', 'LAR', 'QB', 'NFC', 'West', true, true, 75, 214, 38, 9, 'Georgia'),
  ('3139477', 'Patrick Mahomes', 'KC', 'QB', 'AFC', 'West', true, true, 74, 225, 30, 15, 'Texas Tech'),
  ('3912547', 'Sam Darnold', 'SEA', 'QB', 'NFC', 'West', true, true, 75, 225, 29, 14, 'USC'),
  ('4360310', 'Trevor Lawrence', 'JAX', 'QB', 'AFC', 'South', true, true, 78, 220, 26, 16, 'Clemson'),
  ('4241479', 'Tua Tagovailoa', 'ATL', 'QB', 'NFC', 'South', true, true, 73, 225, 28, 1, 'Alabama'),
  ('4360689', 'Tyler Shough', 'NO', 'QB', 'NFC', 'South', true, true, 77, 219, 26, 6, 'Louisville'),
  ('3042519', 'Aaron Jones Sr.', 'MIN', 'RB', 'NFC', 'North', true, true, 70, 208, 31, 33, 'UTEP'),
  ('4890973', 'Ashton Jeanty', 'LV', 'RB', 'AFC', 'West', true, true, 68, 208, 22, 2, 'Boise State'),
  ('4882093', 'Bhayshul Tuten', 'JAX', 'RB', 'AFC', 'South', true, true, 69, 209, 23, 33, 'Virginia Tech'),
  ('4430807', 'Bijan Robinson', 'ATL', 'RB', 'NFC', 'South', true, true, 71, 215, 24, 7, 'Texas'),
  ('4427366', 'Breece Hall', 'NYJ', 'RB', 'AFC', 'East', true, true, 71, 217, 25, 20, 'Iowa State'),
  ('4596448', 'Bucky Irving', 'TB', 'RB', 'NFC', 'South', true, true, 70, 195, 24, 7, 'Oregon'),
  ('4696981', 'Cam Skattebo', 'NYG', 'RB', 'NFC', 'East', true, true, 71, 215, 24, 44, 'Arizona State'),
  ('4362238', 'Chase Brown', 'CIN', 'RB', 'AFC', 'North', true, true, 70, 210, 26, 30, 'Illinois'),
  ('3117251', 'Christian McCaffrey', 'SF', 'RB', 'NFC', 'West', true, true, 71, 210, 30, 23, 'Stanford'),
  ('4241416', 'Chuba Hubbard', 'CAR', 'RB', 'NFC', 'South', true, true, 73, 210, 27, 30, 'Oklahoma State'),
  ('4259545', 'D''Andre Swift', 'CHI', 'RB', 'NFC', 'North', true, true, 68, 204, 27, 4, 'Georgia'),
  ('4035538', 'David Montgomery', 'HOU', 'RB', 'AFC', 'South', true, true, 71, 230, 29, 32, 'Iowa State'),
  ('4429160', 'De''Von Achane', 'MIA', 'RB', 'AFC', 'East', true, true, 69, 191, 24, 28, 'Texas A&M'),
  ('3043078', 'Derrick Henry', 'BAL', 'RB', 'AFC', 'North', true, true, 74, 252, 32, 22, 'Alabama'),
  ('4241985', 'J.K. Dobbins', 'DEN', 'RB', 'AFC', 'West', true, true, 70, 212, 27, 27, 'Ohio State'),
  ('4575131', 'Jacory Croskey-Merritt', 'WAS', 'RB', 'NFC', 'East', true, true, 71, 208, 25, 22, 'Arizona'),
  ('4429795', 'Jahmyr Gibbs', 'DET', 'RB', 'NFC', 'North', true, true, 69, 202, 24, null, 'Alabama'),
  ('4379399', 'James Cook III', 'BUF', 'RB', 'AFC', 'East', true, true, 71, 190, 26, 4, 'Georgia'),
  ('4361579', 'Javonte Williams', 'DAL', 'RB', 'NFC', 'East', true, true, 70, 222, 26, 33, 'North Carolina'),
  ('4569987', 'Jaylen Warren', 'PIT', 'RB', 'AFC', 'North', true, true, 68, 215, 27, 30, 'Oklahoma State'),
  ('4870808', 'Jeremiyah Love', 'ARI', 'RB', 'NFC', 'West', true, true, 72, 212, 21, 4, 'Notre Dame'),
  ('4242335', 'Jonathan Taylor', 'IND', 'RB', 'AFC', 'South', true, true, 70, 226, 27, 28, 'Wisconsin'),
  ('4047365', 'Josh Jacobs', 'GB', 'RB', 'NFC', 'North', true, true, 70, 223, 28, 8, 'Alabama'),
  ('4567048', 'Kenneth Walker III', 'KC', 'RB', 'AFC', 'West', true, true, 69, 211, 25, 9, 'Michigan State'),
  ('4430737', 'Kyren Williams', 'LAR', 'RB', 'NFC', 'West', true, true, 69, 207, 25, 23, 'Notre Dame'),
  ('4685382', 'Omarion Hampton', 'LAC', 'RB', 'AFC', 'West', true, true, 72, 220, 23, 8, 'North Carolina'),
  ('4685702', 'Quinshon Judkins', 'CLE', 'RB', 'AFC', 'North', true, true, 72, 221, 22, 10, 'Ohio State'),
  ('4569173', 'Rhamondre Stevenson', 'NE', 'RB', 'AFC', 'East', true, true, 72, 227, 28, 38, 'Oklahoma'),
  ('3929630', 'Saquon Barkley', 'PHI', 'RB', 'NFC', 'East', true, true, 72, 233, 29, 26, 'Penn State'),
  ('3916148', 'Tony Pollard', 'TEN', 'RB', 'AFC', 'South', true, true, 72, 209, 29, 20, 'Memphis'),
  ('4239996', 'Travis Etienne Jr.', 'NO', 'RB', 'NFC', 'South', true, true, 70, 215, 27, 3, 'Clemson'),
  ('4426385', 'Zach Charbonnet', 'SEA', 'RB', 'NFC', 'West', true, true, 73, 220, 25, 26, 'UCLA'),
  ('4047646', 'A.J. Brown', 'NE', 'WR', 'AFC', 'East', true, true, 73, 226, 29, 1, 'Ole Miss'),
  ('4597500', 'Adonai Mitchell', 'NYJ', 'WR', 'AFC', 'East', true, true, 74, 205, 23, 15, 'Texas'),
  ('4360078', 'Alec Pierce', 'IND', 'WR', 'AFC', 'South', true, true, 75, 211, 26, 14, 'Cincinnati'),
  ('4374302', 'Amon-Ra St. Brown', 'DET', 'WR', 'NFC', 'North', true, true, 72, 202, 26, 14, 'USC'),
  ('4432773', 'Brian Thomas Jr.', 'JAX', 'WR', 'AFC', 'South', true, true, 74, 209, 23, 7, 'LSU'),
  ('4871023', 'Carnell Tate', 'TEN', 'WR', 'AFC', 'South', true, true, 74, 192, 21, 14, 'Ohio State'),
  ('4241389', 'CeeDee Lamb', 'DAL', 'WR', 'NFC', 'East', true, true, 74, 198, 27, 88, 'Oklahoma'),
  ('3116165', 'Chris Godwin Jr.', 'TB', 'WR', 'NFC', 'South', true, true, 73, 209, 30, 14, 'Penn State'),
  ('4361370', 'Chris Olave', 'NO', 'WR', 'NFC', 'South', true, true, 72, 187, 26, 12, 'Ohio State'),
  ('4248528', 'Christian Watson', 'GB', 'WR', 'NFC', 'North', true, true, 76, 215, 27, 9, 'North Dakota State'),
  ('3128429', 'Courtland Sutton', 'DEN', 'WR', 'AFC', 'West', true, true, 76, 216, 30, 14, 'SMU'),
  ('3916945', 'Darius Slayton', 'NYG', 'WR', 'NFC', 'East', true, true, 73, 198, 29, 18, 'Auburn'),
  ('16800', 'Davante Adams', 'LAR', 'WR', 'NFC', 'West', true, true, 73, 204, 33, 17, 'Fresno State'),
  ('3126486', 'Deebo Samuel Sr.', 'SF', 'WR', 'NFC', 'West', true, true, 72, 215, 30, 19, 'South Carolina'),
  ('4241478', 'DeVonta Smith', 'PHI', 'WR', 'NFC', 'East', true, true, 72, 170, 27, 6, 'Alabama'),
  ('3915416', 'DJ Moore', 'BUF', 'WR', 'AFC', 'East', true, true, 72, 213, 29, 2, 'Maryland'),
  ('4047650', 'DK Metcalf', 'PIT', 'WR', 'AFC', 'North', true, true, 76, 229, 28, 4, 'Ole Miss'),
  ('4428850', 'Dontayvion Wicks', 'PHI', 'WR', 'NFC', 'East', true, true, 73, 206, 25, 13, 'Virginia'),
  ('4426502', 'Drake London', 'ATL', 'WR', 'NFC', 'South', true, true, 76, 215, 25, 5, 'USC'),
  ('4567750', 'Emeka Egbuka', 'TB', 'WR', 'NFC', 'South', true, true, 73, 205, 23, 2, 'Ohio State'),
  ('4569618', 'Garrett Wilson', 'NYJ', 'WR', 'AFC', 'East', true, true, 72, 183, 26, 5, 'Ohio State'),
  ('4426354', 'George Pickens', 'DAL', 'WR', 'NFC', 'East', true, true, 75, 200, 25, 3, 'Georgia'),
  ('4362628', 'Ja''Marr Chase', 'CIN', 'WR', 'AFC', 'North', true, true, 72, 205, 26, 1, 'LSU'),
  ('4361409', 'Jahan Dotson', 'ATL', 'WR', 'NFC', 'South', true, true, 71, 184, 26, 4, 'Penn State'),
  ('4695883', 'Jalen Coker', 'CAR', 'WR', 'NFC', 'South', true, true, 75, 213, 24, 18, 'Holy Cross'),
  ('4382466', 'Jalen Nailor', 'LV', 'WR', 'AFC', 'West', true, true, 72, 190, 27, 9, 'Michigan State'),
  ('4249417', 'Jalen Tolbert', 'MIA', 'WR', 'AFC', 'East', true, true, 73, 195, 27, 1, 'South Alabama'),
  ('4426388', 'Jameson Williams', 'DET', 'WR', 'NFC', 'North', true, true, 73, 184, 25, 1, 'Alabama'),
  ('4430878', 'Jaxon Smith-Njigba', 'SEA', 'WR', 'NFC', 'West', true, true, 72, 197, 24, 11, 'Ohio State'),
  ('4362249', 'Jayden Reed', 'GB', 'WR', 'NFC', 'North', true, true, 71, 187, 26, 11, 'Michigan State'),
  ('4372016', 'Jaylen Waddle', 'DEN', 'WR', 'AFC', 'West', true, true, 70, 185, 27, 17, 'Alabama'),
  ('4241463', 'Jerry Jeudy', 'CLE', 'WR', 'AFC', 'North', true, true, 73, 195, 27, 3, 'Alabama'),
  ('4429205', 'Jordan Addison', 'MIN', 'WR', 'NFC', 'North', true, true, 71, 179, 24, 3, 'USC'),
  ('4880281', 'Jordyn Tyson', 'NO', 'WR', 'NFC', 'South', true, true, 74, 203, 22, null, 'Arizona State'),
  ('4688813', 'Josh Downs', 'IND', 'WR', 'AFC', 'South', true, true, 69, 171, 25, 2, 'North Carolina'),
  ('4262921', 'Justin Jefferson', 'MIN', 'WR', 'NFC', 'North', true, true, 73, 195, 27, 18, 'LSU'),
  ('4870653', 'KC Concepcion', 'CLE', 'WR', 'AFC', 'North', true, true, 72, 190, 21, 1, 'Texas A&M'),
  ('4373678', 'Khalil Shakir', 'BUF', 'WR', 'AFC', 'East', true, true, 72, 190, 26, 10, 'Boise State'),
  ('4612826', 'Ladd McConkey', 'LAC', 'WR', 'AFC', 'West', true, true, 72, 185, 24, 15, 'Georgia'),
  ('4685278', 'Luther Burden III', 'CHI', 'WR', 'NFC', 'North', true, true, 72, 210, 22, 10, 'Missouri'),
  ('4595348', 'Malik Nabers', 'NYG', 'WR', 'NFC', 'East', true, true, 72, 200, 23, 1, 'LSU'),
  ('4569603', 'Malik Washington', 'MIA', 'WR', 'AFC', 'East', true, true, 68, 195, 25, 6, 'Virginia'),
  ('4432708', 'Marvin Harrison Jr.', 'ARI', 'WR', 'NFC', 'West', true, true, 75, 220, 24, 18, 'Ohio State'),
  ('4035687', 'Michael Pittman Jr.', 'PIT', 'WR', 'AFC', 'North', true, true, 76, 223, 28, 11, 'USC'),
  ('4360761', 'Michael Wilson', 'ARI', 'WR', 'NFC', 'West', true, true, 74, 213, 26, 14, 'Stanford'),
  ('16737', 'Mike Evans', 'SF', 'WR', 'NFC', 'West', true, true, 77, 231, 33, 5, 'Texas A&M'),
  ('4258173', 'Nico Collins', 'HOU', 'WR', 'AFC', 'South', true, true, 76, 222, 27, 12, 'Michigan'),
  ('4432620', 'Parker Washington', 'JAX', 'WR', 'AFC', 'South', true, true, 70, 204, 24, 11, 'Penn State'),
  ('4426515', 'Puka Nacua', 'LAR', 'WR', 'NFC', 'West', true, true, 74, 216, 25, 12, 'BYU'),
  ('4429025', 'Quentin Johnston', 'LAC', 'WR', 'AFC', 'West', true, true, 74, 208, 24, 1, 'TCU'),
  ('4428331', 'Rashee Rice', 'KC', 'WR', 'AFC', 'West', true, true, 73, 204, 26, 4, 'SMU'),
  ('4032473', 'Rashid Shaheed', 'SEA', 'WR', 'NFC', 'West', true, true, 72, 180, 27, 22, 'Weber State'),
  ('4360939', 'Rashod Bateman', 'BAL', 'WR', 'AFC', 'North', true, true, 73, 193, 26, 7, 'Minnesota'),
  ('4431299', 'Rome Odunze', 'CHI', 'WR', 'NFC', 'North', true, true, 75, 214, 24, 15, 'Washington'),
  ('4361432', 'Romeo Doubs', 'NE', 'WR', 'AFC', 'East', true, true, 74, 210, 26, 87, 'Nevada'),
  ('2976212', 'Stefon Diggs', 'WAS', 'WR', 'NFC', 'East', true, true, 72, 191, 32, 18, 'Maryland'),
  ('4239993', 'Tee Higgins', 'CIN', 'WR', 'AFC', 'North', true, true, 76, 220, 27, 5, 'Clemson'),
  ('3121422', 'Terry McLaurin', 'WAS', 'WR', 'NFC', 'East', true, true, 72, 210, 30, 17, 'Ohio State'),
  ('4685472', 'Tetairoa McMillan', 'CAR', 'WR', 'NFC', 'South', true, true, 77, 212, 23, 4, 'Arizona'),
  ('4428718', 'Tre Tucker', 'LV', 'WR', 'AFC', 'West', true, true, 68, 182, 25, 1, 'Cincinnati'),
  ('4569587', 'Wan''Dale Robinson', 'TEN', 'WR', 'AFC', 'South', true, true, 68, 185, 25, 4, 'Kentucky'),
  ('4686422', 'Xavier Hutchinson', 'HOU', 'WR', 'AFC', 'South', true, true, 75, 210, 26, 19, 'Iowa State'),
  ('4683062', 'Xavier Worthy', 'KC', 'WR', 'AFC', 'West', true, true, 71, 165, 23, 1, 'Texas'),
  ('4429615', 'Zay Flowers', 'BAL', 'WR', 'AFC', 'North', true, true, 69, 183, 25, 4, 'Boston College'),
  ('4576297', 'AJ Barner', 'SEA', 'TE', 'NFC', 'West', true, true, 78, 251, 24, 88, 'Michigan'),
  ('4430539', 'Brenton Strange', 'JAX', 'TE', 'AFC', 'South', true, true, 76, 253, 25, 85, 'Penn State'),
  ('4432665', 'Brock Bowers', 'LV', 'TE', 'AFC', 'West', true, true, 76, 235, 23, 89, 'Georgia'),
  ('4243331', 'Cade Otton', 'TB', 'TE', 'NFC', 'South', true, true, 77, 247, 27, 88, 'Washington'),
  ('4241263', 'Charlie Kolar', 'LAC', 'TE', 'AFC', 'West', true, true, 78, 250, 27, 88, 'Iowa State'),
  ('4360635', 'Chig Okonkwo', 'WAS', 'TE', 'NFC', 'East', true, true, 75, 238, 26, 85, 'Maryland'),
  ('4242557', 'Colby Parkinson', 'LAR', 'TE', 'NFC', 'West', true, true, 79, 266, 27, 84, 'Stanford'),
  ('4723086', 'Colston Loveland', 'CHI', 'TE', 'NFC', 'North', true, true, 78, 241, 22, 84, 'Michigan'),
  ('3121023', 'Dallas Goedert', 'PHI', 'TE', 'NFC', 'East', true, true, 77, 256, 31, 88, 'South Dakota State'),
  ('4385690', 'Dalton Kincaid', 'BUF', 'TE', 'AFC', 'East', true, true, 75, 246, 26, 86, 'Utah'),
  ('3117256', 'Dalton Schultz', 'HOU', 'TE', 'AFC', 'South', true, true, 77, 242, 30, 86, 'Stanford'),
  ('3051876', 'Evan Engram', 'DEN', 'TE', 'AFC', 'West', true, true, 75, 240, 31, 1, 'Ole Miss'),
  ('3040151', 'George Kittle', 'SF', 'TE', 'NFC', 'West', true, true, 76, 250, 32, 85, 'Iowa'),
  ('4367209', 'Greg Dulcich', 'MIA', 'TE', 'AFC', 'East', true, true, 76, 245, 26, 85, 'UCLA'),
  ('4686728', 'Gunnar Helm', 'TEN', 'TE', 'AFC', 'South', true, true, 77, 241, 23, 84, 'Texas'),
  ('5083076', 'Harold Fannin Jr.', 'CLE', 'TE', 'AFC', 'North', true, true, 76, 241, 22, 44, 'Bowling Green'),
  ('3046439', 'Hunter Henry', 'NE', 'TE', 'AFC', 'East', true, true, 77, 249, 31, 85, 'Arkansas'),
  ('4361050', 'Isaiah Likely', 'NYG', 'TE', 'NFC', 'East', true, true, 76, 241, 26, 9, 'Coastal Carolina'),
  ('4242355', 'Jake Ferguson', 'DAL', 'TE', 'NFC', 'East', true, true, 77, 250, 27, 87, 'Wisconsin'),
  ('3929645', 'Juwan Johnson', 'NO', 'TE', 'NFC', 'South', true, true, 76, 231, 29, 83, 'Oregon'),
  ('4360248', 'Kyle Pitts Sr.', 'ATL', 'TE', 'NFC', 'South', true, true, 78, 250, 25, 8, 'Florida'),
  ('3116365', 'Mark Andrews', 'BAL', 'TE', 'AFC', 'North', true, true, 77, 250, 30, 89, 'Oklahoma'),
  ('4808766', 'Mason Taylor', 'NYJ', 'TE', 'AFC', 'East', true, true, 77, 251, 22, 85, 'LSU'),
  ('3116164', 'Mike Gesicki', 'CIN', 'TE', 'AFC', 'North', true, true, 78, 245, 30, 88, 'Penn State'),
  ('4361411', 'Pat Freiermuth', 'PIT', 'TE', 'AFC', 'North', true, true, 77, 258, 27, 88, 'Penn State'),
  ('4430027', 'Sam LaPorta', 'DET', 'TE', 'NFC', 'North', true, true, 75, 245, 25, 87, 'Iowa'),
  ('4036133', 'T.J. Hockenson', 'MIN', 'TE', 'NFC', 'North', true, true, 77, 248, 29, 87, 'Iowa'),
  ('4372780', 'Tommy Tremble', 'CAR', 'TE', 'NFC', 'South', true, true, 76, 250, 26, 82, 'Notre Dame'),
  ('15847', 'Travis Kelce', 'KC', 'TE', 'AFC', 'West', true, true, 77, 250, 36, 87, 'Cincinnati'),
  ('4361307', 'Trey McBride', 'ARI', 'TE', 'NFC', 'West', true, true, 76, 246, 26, 85, 'Colorado State'),
  ('4572680', 'Tucker Kraft', 'GB', 'TE', 'NFC', 'North', true, true, 77, 259, 25, 85, 'South Dakota State'),
  ('4431459', 'Tyler Warren', 'IND', 'TE', 'AFC', 'South', true, true, 78, 256, 24, 84, 'Penn State')
on conflict (espn_id) do update set
  name = excluded.name,
  team = excluded.team,
  position = excluded.position,
  conference = excluded.conference,
  division = excluded.division,
  answerable = excluded.answerable,
  guessable = excluded.guessable,
  height_in = excluded.height_in,
  weight_lb = excluded.weight_lb,
  age = excluded.age,
  jersey = excluded.jersey,
  college = excluded.college;

-- Slots are the running order the daily pick walks, one a day, so only
-- players who can be the answer get one.
--
-- DEALT FRESH every time rather than appended to. The seed used to keep
-- existing slots so days already scheduled would not move, which is right
-- when a weekly sync changes a handful of players - and wrong here,
-- because the pool itself changed shape. Slots left over from a pool of
-- 1,441 are scattered across 1..1441 while ensure_daily_puzzle now walks
-- 1..160: most days would find no row at their slot and fall through to
-- the same few players over and over.
--
-- Safe to re-deal because ensure_daily_puzzle returns the daily_puzzles
-- row for a date when one exists and only picks a slot when it does not -
-- so this can only change days nobody has played yet.
--
-- Two statements because slot is `integer unique`, and one UPDATE that
-- permutes the values trips the constraint on the way through even though
-- the end state is fine.
update public.puzzle_players set slot = null where slot is not null;

update public.puzzle_players
   set slot = sub.next_slot
  from (
    select espn_id, row_number() over (order by random()) as next_slot
      from public.puzzle_players
     where answerable
  ) sub
 where public.puzzle_players.espn_id = sub.espn_id;

-- Expect 160 / 160, with every other row kept but switched off.
select count(*) filter (where slot is not null) as in_rotation,
       count(*) filter (where guessable)        as guessable,
       count(*)                                 as rows_kept
  from public.puzzle_players;
