// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// Every active player, for the daily puzzle. You can guess anyone in
// here; the answer is only ever drawn from the ones marked answerable,
// which means ESPN's depth chart mentions them somewhere. An answer pool
// of all 1,700 would include third-string guards nobody can name.
//
// Empty until the script has been run once, and the puzzle falls back to
// the five position rosters when it is - see src/data/puzzlePlayers.ts -
// so an unsynced checkout plays a smaller game rather than none.
import { TeamAbbr } from "@/data/teams";

export type ActivePlayer = {
  espnId: string;
  name: string;
  team: TeamAbbr;
  // ESPN's own abbreviation: QB, RB, WR, TE, K, but also OT, CB, EDGE,
  // LS and the rest. Not one of our five buckets.
  position: string;
  // On a depth chart somewhere, at any rank. Only these can be the
  // answer.
  answerable: boolean;
  heightIn?: number;
  weightLb?: number;
  age?: number;
  jersey?: number;
  college?: string;
};

export const ACTIVE_PLAYERS: ActivePlayer[] = [];
