// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// Every active player, for the daily puzzle. You can guess anyone in
// here; the answer is only ever drawn from the ones marked answerable,
// which means ESPN's depth chart mentions them somewhere. An answer pool
// of all 1,700 would include third-string guards nobody can name.
//
// Empty until the script has been run once, and the puzzle falls back to
// the five position rosters when it is - see src/data/puzzlePlayers.ts -
// so an unsynced checkout plays a smaller game rather than none.
import { TeamAbbr } from "@/data/teams";

export type ActivePlayer = {
  espnId: string;
  name: string;
  team: TeamAbbr;
  // ESPN's own abbreviation: QB, RB, WR, TE, K, but also OT, CB, EDGE,
  // LS and the rest. Not one of our five buckets.
  position: string;
  // Best depth chart rank across every slot they are listed at, or
  // absent when the chart does not rank them. 1 is a starter.
  //
  // Stored as the number rather than a yes/no so which ranks count as
  // answerable can be retuned without another trip to ESPN - see
  // ANSWER_MAX_DEPTH_RANK in src/data/puzzlePlayers.ts.
  depthRank?: number;
  heightIn?: number;
  weightLb?: number;
  age?: number;
  jersey?: number;
  college?: string;
};

export const ACTIVE_PLAYERS: ActivePlayer[] = [];
