// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The head coach of each team, with the ESPN id their headshot is keyed
// on and the headshot URL the sync actually confirmed - coaches do not
// live at the same image path as players, and the path has moved, so the
// working one is recorded rather than rebuilt from a guess.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type Coach = {
  espnId: string;
  name: string;
  team: TeamAbbr;
  // Empty when ESPN had no headshot at any known path. The chip falls
  // back to a team-coloured tile, which still names and colours the man.
  imageUrl: string;
};

export const HEAD_COACHES: Coach[] = [
];
