// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The head coach of each team, with the ESPN id their headshot is keyed
// on and the headshot URL the sync actually confirmed - coaches do not
// live at the same image path as players, and the path has moved, so the
// working one is recorded rather than rebuilt from a guess.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type Coach = {
  espnId: string;
  name: string;
  team: TeamAbbr;
  // Empty when ESPN had no headshot at any known path. The chip falls
  // back to a team-coloured tile, which still names and colours the man.
  imageUrl: string;
};

export const HEAD_COACHES: Coach[] = [
  { espnId: "558", name: "Aaron Glenn", team: "NYJ", imageUrl: "" },
  { espnId: "17553", name: "Andy Reid", team: "KC", imageUrl: "" },
  { espnId: "2180177", name: "Ben Johnson", team: "CHI", imageUrl: "" },
  { espnId: "17530", name: "Brian Schottenheimer", team: "DAL", imageUrl: "" },
  { espnId: "1832", name: "Dan Campbell", team: "DET", imageUrl: "" },
  { espnId: "2485644", name: "Dan Quinn", team: "WAS", imageUrl: "" },
  { espnId: "17762", name: "Dave Canales", team: "CAR", imageUrl: "" },
  { espnId: "9619", name: "DeMeco Ryans", team: "HOU", imageUrl: "https://a.espncdn.com/i/headshots/nfl/players/full/9619.png" },
  { espnId: "4607510", name: "Jeff Hafley", team: "MIA", imageUrl: "" },
  { espnId: "5173599", name: "Jesse Minter", team: "BAL", imageUrl: "" },
  { espnId: "27", name: "Jim Harbaugh", team: "LAC", imageUrl: "" },
  { espnId: "2471205", name: "Joe Brady", team: "BUF", imageUrl: "" },
  { espnId: "17587", name: "John Harbaugh", team: "NYG", imageUrl: "" },
  { espnId: "14882", name: "Kellen Moore", team: "NO", imageUrl: "https://a.espncdn.com/i/headshots/nfl/players/full/14882.png" },
  { espnId: "2146711", name: "Kevin O'Connell", team: "MIN", imageUrl: "" },
  { espnId: "4408695", name: "Kevin Stefanski", team: "ATL", imageUrl: "" },
  { espnId: "2181979", name: "Klint Kubiak", team: "LV", imageUrl: "" },
  { espnId: "17533", name: "Kyle Shanahan", team: "SF", imageUrl: "" },
  { espnId: "2161829", name: "Liam Coen", team: "JAX", imageUrl: "" },
  { espnId: "4082797", name: "Matt LaFleur", team: "GB", imageUrl: "" },
  { espnId: "4872749", name: "Mike LaFleur", team: "ARI", imageUrl: "" },
  { espnId: "5044374", name: "Mike Macdonald", team: "SEA", imageUrl: "" },
  { espnId: "17578", name: "Mike McCarthy", team: "PIT", imageUrl: "" },
  { espnId: "1257", name: "Mike Vrabel", team: "NE", imageUrl: "https://a.espncdn.com/i/headshots/nfl/players/full/1257.png" },
  { espnId: "4372439", name: "Nick Sirianni", team: "PHI", imageUrl: "" },
  { espnId: "4085970", name: "Robert Saleh", team: "TEN", imageUrl: "" },
  { espnId: "2499338", name: "Sean McVay", team: "LAR", imageUrl: "" },
  { espnId: "17567", name: "Sean Payton", team: "DEN", imageUrl: "" },
  { espnId: "2126648", name: "Shane Steichen", team: "IND", imageUrl: "" },
  { espnId: "7157", name: "Todd Bowles", team: "TB", imageUrl: "https://a.espncdn.com/i/headshots/nfl/players/full/7157.png" },
  { espnId: "3017859", name: "Todd Monken", team: "CLE", imageUrl: "" },
  { espnId: "2184471", name: "Zac Taylor", team: "CIN", imageUrl: "" },
];
