// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The running backs each team lines up, with the ESPN player id their
// headshot is keyed on. Generated rather than typed out because both
// halves of a row go stale on their own schedule: depth charts change
// week to week, and a player id guessed wrong doesn't fail loudly - it
// renders a different person's face under the right name.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type RunningBack = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
};

export const RUNNING_BACKS: RunningBack[] = [
  { espnId: "3042519", name: "Aaron Jones Sr.", team: "MIN" },
  { espnId: "4890973", name: "Ashton Jeanty", team: "LV" },
  { espnId: "4882093", name: "Bhayshul Tuten", team: "JAX" },
  { espnId: "4430807", name: "Bijan Robinson", team: "ATL" },
  { espnId: "4427366", name: "Breece Hall", team: "NYJ" },
  { espnId: "4596448", name: "Bucky Irving", team: "TB" },
  { espnId: "4696981", name: "Cam Skattebo", team: "NYG" },
  { espnId: "4362238", name: "Chase Brown", team: "CIN" },
  { espnId: "3117251", name: "Christian McCaffrey", team: "SF" },
  { espnId: "4241416", name: "Chuba Hubbard", team: "CAR" },
  { espnId: "4259545", name: "D'Andre Swift", team: "CHI" },
  { espnId: "4035538", name: "David Montgomery", team: "HOU" },
  { espnId: "4429160", name: "De'Von Achane", team: "MIA" },
  { espnId: "3043078", name: "Derrick Henry", team: "BAL" },
  { espnId: "4241985", name: "J.K. Dobbins", team: "DEN" },
  { espnId: "4575131", name: "Jacory Croskey-Merritt", team: "WAS" },
  { espnId: "4429795", name: "Jahmyr Gibbs", team: "DET" },
  { espnId: "4379399", name: "James Cook III", team: "BUF" },
  { espnId: "4361579", name: "Javonte Williams", team: "DAL" },
  { espnId: "4569987", name: "Jaylen Warren", team: "PIT" },
  { espnId: "4870808", name: "Jeremiyah Love", team: "ARI" },
  { espnId: "4242335", name: "Jonathan Taylor", team: "IND" },
  { espnId: "4047365", name: "Josh Jacobs", team: "GB" },
  { espnId: "4567048", name: "Kenneth Walker III", team: "KC" },
  { espnId: "4430737", name: "Kyren Williams", team: "LAR" },
  { espnId: "4685382", name: "Omarion Hampton", team: "LAC" },
  { espnId: "4685702", name: "Quinshon Judkins", team: "CLE" },
  { espnId: "4569173", name: "Rhamondre Stevenson", team: "NE" },
  { espnId: "3929630", name: "Saquon Barkley", team: "PHI" },
  { espnId: "3916148", name: "Tony Pollard", team: "TEN" },
  { espnId: "4239996", name: "Travis Etienne Jr.", team: "NO" },
  { espnId: "4426385", name: "Zach Charbonnet", team: "SEA" },
];
