// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The tight ends each team lines up, with the ESPN player id their
// headshot is keyed on. Generated rather than typed out because both
// halves of a row go stale on their own schedule: depth charts change
// week to week, and a player id guessed wrong doesn't fail loudly - it
// renders a different person's face under the right name.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type TightEnd = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
};

export const TIGHT_ENDS: TightEnd[] = [
  { espnId: "4576297", name: "AJ Barner", team: "SEA" },
  { espnId: "4430539", name: "Brenton Strange", team: "JAX" },
  { espnId: "4432665", name: "Brock Bowers", team: "LV" },
  { espnId: "4243331", name: "Cade Otton", team: "TB" },
  { espnId: "4360635", name: "Chig Okonkwo", team: "WAS" },
  { espnId: "4242557", name: "Colby Parkinson", team: "LAR" },
  { espnId: "4723086", name: "Colston Loveland", team: "CHI" },
  { espnId: "3121023", name: "Dallas Goedert", team: "PHI" },
  { espnId: "4385690", name: "Dalton Kincaid", team: "BUF" },
  { espnId: "3117256", name: "Dalton Schultz", team: "HOU" },
  { espnId: "3051876", name: "Evan Engram", team: "DEN" },
  { espnId: "3040151", name: "George Kittle", team: "SF" },
  { espnId: "4367209", name: "Greg Dulcich", team: "MIA" },
  { espnId: "4686728", name: "Gunnar Helm", team: "TEN" },
  { espnId: "5083076", name: "Harold Fannin Jr.", team: "CLE" },
  { espnId: "3046439", name: "Hunter Henry", team: "NE" },
  { espnId: "4361050", name: "Isaiah Likely", team: "NYG" },
  { espnId: "4242355", name: "Jake Ferguson", team: "DAL" },
  { espnId: "3929645", name: "Juwan Johnson", team: "NO" },
  { espnId: "5083315", name: "Kenyon Sadiq", team: "NYJ" },
  { espnId: "4360248", name: "Kyle Pitts Sr.", team: "ATL" },
  { espnId: "3116365", name: "Mark Andrews", team: "BAL" },
  { espnId: "3116164", name: "Mike Gesicki", team: "CIN" },
  { espnId: "4595342", name: "Oronde Gadsden", team: "LAC" },
  { espnId: "4361411", name: "Pat Freiermuth", team: "PIT" },
  { espnId: "4430027", name: "Sam LaPorta", team: "DET" },
  { espnId: "4036133", name: "T.J. Hockenson", team: "MIN" },
  { espnId: "4372780", name: "Tommy Tremble", team: "CAR" },
  { espnId: "15847", name: "Travis Kelce", team: "KC" },
  { espnId: "4361307", name: "Trey McBride", team: "ARI" },
  { espnId: "4572680", name: "Tucker Kraft", team: "GB" },
  { espnId: "4431459", name: "Tyler Warren", team: "IND" },
];
