// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The tight ends each team lines up, with the ESPN player id their
// headshot is keyed on. Generated rather than typed out because both
// halves of a row go stale on their own schedule: depth charts change
// week to week, and a player id guessed wrong doesn't fail loudly - it
// renders a different person's face under the right name.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import type { TeamAbbr } from "@/data/teams";

export type TightEnd = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
  // Where this player sits on their own team's chart: 1 is the starter,
  // 2 the next one down. The rows below are sorted by NAME, so without
  // this the only way to pick "the top two receivers on the Vikings" was
  // to take the first two alphabetically - which is how Justin Jefferson
  // came to be left off a graphic on a live stream.
  depth?: number;
  // Hint columns for the daily player puzzle. Optional because ESPN does
  // not publish all of them for everyone; the puzzle hides a column it
  // has no values for rather than showing a row of "?".
  heightIn?: number;
  weightLb?: number;
  age?: number;
  jersey?: number;
  college?: string;
};

export const TIGHT_ENDS: TightEnd[] = [
  { espnId: "4576297", name: "AJ Barner", team: "SEA", depth: 1, heightIn: 78, weightLb: 251, age: 24, jersey: 88 },
  { espnId: "4430539", name: "Brenton Strange", team: "JAX", depth: 1, heightIn: 76, weightLb: 253, age: 25, jersey: 85 },
  { espnId: "4432665", name: "Brock Bowers", team: "LV", depth: 1, heightIn: 76, weightLb: 235, age: 23, jersey: 89 },
  { espnId: "4243331", name: "Cade Otton", team: "TB", depth: 1, heightIn: 77, weightLb: 247, age: 27, jersey: 88 },
  { espnId: "4241263", name: "Charlie Kolar", team: "LAC", depth: 1, heightIn: 78, weightLb: 250, age: 27, jersey: 88 },
  { espnId: "4360635", name: "Chig Okonkwo", team: "WAS", depth: 1, heightIn: 75, weightLb: 238, age: 26, jersey: 85 },
  { espnId: "4242557", name: "Colby Parkinson", team: "LAR", depth: 1, heightIn: 79, weightLb: 266, age: 27, jersey: 84 },
  { espnId: "4723086", name: "Colston Loveland", team: "CHI", depth: 1, heightIn: 78, weightLb: 241, age: 22, jersey: 84 },
  { espnId: "3121023", name: "Dallas Goedert", team: "PHI", depth: 1, heightIn: 77, weightLb: 256, age: 31, jersey: 88 },
  { espnId: "4385690", name: "Dalton Kincaid", team: "BUF", depth: 1, heightIn: 75, weightLb: 246, age: 26, jersey: 86 },
  { espnId: "3117256", name: "Dalton Schultz", team: "HOU", depth: 1, heightIn: 77, weightLb: 242, age: 30, jersey: 86 },
  { espnId: "3051876", name: "Evan Engram", team: "DEN", depth: 1, heightIn: 75, weightLb: 240, age: 31, jersey: 1 },
  { espnId: "3040151", name: "George Kittle", team: "SF", depth: 1, heightIn: 76, weightLb: 250, age: 32, jersey: 85 },
  { espnId: "4367209", name: "Greg Dulcich", team: "MIA", depth: 1, heightIn: 76, weightLb: 245, age: 26, jersey: 85 },
  { espnId: "4686728", name: "Gunnar Helm", team: "TEN", depth: 1, heightIn: 77, weightLb: 241, age: 23, jersey: 84 },
  { espnId: "5083076", name: "Harold Fannin Jr.", team: "CLE", depth: 1, heightIn: 76, weightLb: 241, age: 22, jersey: 44 },
  { espnId: "3046439", name: "Hunter Henry", team: "NE", depth: 1, heightIn: 77, weightLb: 249, age: 31, jersey: 85 },
  { espnId: "4361050", name: "Isaiah Likely", team: "NYG", depth: 1, heightIn: 76, weightLb: 241, age: 26, jersey: 9 },
  { espnId: "4242355", name: "Jake Ferguson", team: "DAL", depth: 1, heightIn: 77, weightLb: 250, age: 27, jersey: 87 },
  { espnId: "3929645", name: "Juwan Johnson", team: "NO", depth: 1, heightIn: 76, weightLb: 231, age: 29, jersey: 83 },
  { espnId: "4360248", name: "Kyle Pitts Sr.", team: "ATL", depth: 1, heightIn: 78, weightLb: 250, age: 25, jersey: 8 },
  { espnId: "3116365", name: "Mark Andrews", team: "BAL", depth: 1, heightIn: 77, weightLb: 250, age: 30, jersey: 89 },
  { espnId: "4808766", name: "Mason Taylor", team: "NYJ", depth: 1, heightIn: 77, weightLb: 251, age: 22, jersey: 85 },
  { espnId: "3116164", name: "Mike Gesicki", team: "CIN", depth: 1, heightIn: 78, weightLb: 245, age: 30, jersey: 88 },
  { espnId: "4361411", name: "Pat Freiermuth", team: "PIT", depth: 1, heightIn: 77, weightLb: 258, age: 27, jersey: 88 },
  { espnId: "4430027", name: "Sam LaPorta", team: "DET", depth: 1, heightIn: 75, weightLb: 245, age: 25, jersey: 87 },
  { espnId: "4036133", name: "T.J. Hockenson", team: "MIN", depth: 1, heightIn: 77, weightLb: 248, age: 29, jersey: 87 },
  { espnId: "4372780", name: "Tommy Tremble", team: "CAR", depth: 1, heightIn: 76, weightLb: 250, age: 26, jersey: 82 },
  { espnId: "15847", name: "Travis Kelce", team: "KC", depth: 1, heightIn: 77, weightLb: 250, age: 36, jersey: 87 },
  { espnId: "4361307", name: "Trey McBride", team: "ARI", depth: 1, heightIn: 76, weightLb: 246, age: 26, jersey: 85 },
  { espnId: "4572680", name: "Tucker Kraft", team: "GB", depth: 1, heightIn: 77, weightLb: 259, age: 25, jersey: 85 },
  { espnId: "4431459", name: "Tyler Warren", team: "IND", depth: 1, heightIn: 78, weightLb: 256, age: 24, jersey: 84 },
];
