// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The wide receivers each team lines up, with the ESPN player id their
// headshot is keyed on. Generated rather than typed out because both
// halves of a row go stale on their own schedule: depth charts change
// week to week, and a player id guessed wrong doesn't fail loudly - it
// renders a different person's face under the right name.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type WideReceiver = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
  // Hint columns for the daily player puzzle. Optional because ESPN does
  // not publish all of them for everyone; the puzzle hides a column it
  // has no values for rather than showing a row of "?".
  heightIn?: number;
  weightLb?: number;
  age?: number;
  jersey?: number;
  college?: string;
};

export const WIDE_RECEIVERS: WideReceiver[] = [
  { espnId: "4047646", name: "A.J. Brown", team: "NE", heightIn: 73, weightLb: 226, age: 29, jersey: 1 },
  { espnId: "4597500", name: "Adonai Mitchell", team: "NYJ", heightIn: 74, weightLb: 205, age: 23, jersey: 15 },
  { espnId: "4360078", name: "Alec Pierce", team: "IND", heightIn: 75, weightLb: 211, age: 26, jersey: 14 },
  { espnId: "4374302", name: "Amon-Ra St. Brown", team: "DET", heightIn: 72, weightLb: 202, age: 26, jersey: 14 },
  { espnId: "4432773", name: "Brian Thomas Jr.", team: "JAX", heightIn: 74, weightLb: 209, age: 23, jersey: 7 },
  { espnId: "4871023", name: "Carnell Tate", team: "TEN", heightIn: 74, weightLb: 192, age: 21, jersey: 14 },
  { espnId: "4241389", name: "CeeDee Lamb", team: "DAL", heightIn: 74, weightLb: 198, age: 27, jersey: 88 },
  { espnId: "3116165", name: "Chris Godwin Jr.", team: "TB", heightIn: 73, weightLb: 209, age: 30, jersey: 14 },
  { espnId: "4361370", name: "Chris Olave", team: "NO", heightIn: 72, weightLb: 187, age: 26, jersey: 12 },
  { espnId: "4248528", name: "Christian Watson", team: "GB", heightIn: 76, weightLb: 215, age: 27, jersey: 9 },
  { espnId: "3128429", name: "Courtland Sutton", team: "DEN", heightIn: 76, weightLb: 216, age: 30, jersey: 14 },
  { espnId: "3916945", name: "Darius Slayton", team: "NYG", heightIn: 73, weightLb: 198, age: 29, jersey: 18 },
  { espnId: "16800", name: "Davante Adams", team: "LAR", heightIn: 73, weightLb: 204, age: 33, jersey: 17 },
  { espnId: "3126486", name: "Deebo Samuel Sr.", team: "SF", heightIn: 72, weightLb: 215, age: 30, jersey: 19 },
  { espnId: "4241478", name: "DeVonta Smith", team: "PHI", heightIn: 72, weightLb: 170, age: 27, jersey: 6 },
  { espnId: "3915416", name: "DJ Moore", team: "BUF", heightIn: 72, weightLb: 213, age: 29, jersey: 2 },
  { espnId: "4047650", name: "DK Metcalf", team: "PIT", heightIn: 76, weightLb: 229, age: 28, jersey: 4 },
  { espnId: "4428850", name: "Dontayvion Wicks", team: "PHI", heightIn: 73, weightLb: 206, age: 25, jersey: 13 },
  { espnId: "4426502", name: "Drake London", team: "ATL", heightIn: 76, weightLb: 215, age: 25, jersey: 5 },
  { espnId: "4567750", name: "Emeka Egbuka", team: "TB", heightIn: 73, weightLb: 205, age: 23, jersey: 2 },
  { espnId: "4569618", name: "Garrett Wilson", team: "NYJ", heightIn: 72, weightLb: 183, age: 26, jersey: 5 },
  { espnId: "4426354", name: "George Pickens", team: "DAL", heightIn: 75, weightLb: 200, age: 25, jersey: 3 },
  { espnId: "4362628", name: "Ja'Marr Chase", team: "CIN", heightIn: 72, weightLb: 205, age: 26, jersey: 1 },
  { espnId: "4361409", name: "Jahan Dotson", team: "ATL", heightIn: 71, weightLb: 184, age: 26, jersey: 4 },
  { espnId: "4695883", name: "Jalen Coker", team: "CAR", heightIn: 75, weightLb: 213, age: 24, jersey: 18 },
  { espnId: "4382466", name: "Jalen Nailor", team: "LV", heightIn: 72, weightLb: 190, age: 27, jersey: 9 },
  { espnId: "4249417", name: "Jalen Tolbert", team: "MIA", heightIn: 73, weightLb: 195, age: 27, jersey: 1 },
  { espnId: "4426388", name: "Jameson Williams", team: "DET", heightIn: 73, weightLb: 184, age: 25, jersey: 1 },
  { espnId: "4430878", name: "Jaxon Smith-Njigba", team: "SEA", heightIn: 72, weightLb: 197, age: 24, jersey: 11 },
  { espnId: "4362249", name: "Jayden Reed", team: "GB", heightIn: 71, weightLb: 187, age: 26, jersey: 11 },
  { espnId: "4372016", name: "Jaylen Waddle", team: "DEN", heightIn: 70, weightLb: 185, age: 27, jersey: 17 },
  { espnId: "4241463", name: "Jerry Jeudy", team: "CLE", heightIn: 73, weightLb: 195, age: 27, jersey: 3 },
  { espnId: "4429205", name: "Jordan Addison", team: "MIN", heightIn: 71, weightLb: 179, age: 24, jersey: 3 },
  { espnId: "4880281", name: "Jordyn Tyson", team: "NO", heightIn: 74, weightLb: 203, age: 22 },
  { espnId: "4688813", name: "Josh Downs", team: "IND", heightIn: 69, weightLb: 171, age: 25, jersey: 2 },
  { espnId: "4262921", name: "Justin Jefferson", team: "MIN", heightIn: 73, weightLb: 195, age: 27, jersey: 18 },
  { espnId: "4870653", name: "KC Concepcion", team: "CLE", heightIn: 72, weightLb: 190, age: 21, jersey: 1 },
  { espnId: "4373678", name: "Khalil Shakir", team: "BUF", heightIn: 72, weightLb: 190, age: 26, jersey: 10 },
  { espnId: "4612826", name: "Ladd McConkey", team: "LAC", heightIn: 72, weightLb: 185, age: 24, jersey: 15 },
  { espnId: "4685278", name: "Luther Burden III", team: "CHI", heightIn: 72, weightLb: 210, age: 22, jersey: 10 },
  { espnId: "4595348", name: "Malik Nabers", team: "NYG", heightIn: 72, weightLb: 200, age: 23, jersey: 1 },
  { espnId: "4569603", name: "Malik Washington", team: "MIA", heightIn: 68, weightLb: 195, age: 25, jersey: 6 },
  { espnId: "4432708", name: "Marvin Harrison Jr.", team: "ARI", heightIn: 75, weightLb: 220, age: 24, jersey: 18 },
  { espnId: "4035687", name: "Michael Pittman Jr.", team: "PIT", heightIn: 76, weightLb: 223, age: 28, jersey: 11 },
  { espnId: "4360761", name: "Michael Wilson", team: "ARI", heightIn: 74, weightLb: 213, age: 26, jersey: 14 },
  { espnId: "16737", name: "Mike Evans", team: "SF", heightIn: 77, weightLb: 231, age: 33, jersey: 5 },
  { espnId: "4258173", name: "Nico Collins", team: "HOU", heightIn: 76, weightLb: 222, age: 27, jersey: 12 },
  { espnId: "4432620", name: "Parker Washington", team: "JAX", heightIn: 70, weightLb: 204, age: 24, jersey: 11 },
  { espnId: "4426515", name: "Puka Nacua", team: "LAR", heightIn: 74, weightLb: 216, age: 25, jersey: 12 },
  { espnId: "4429025", name: "Quentin Johnston", team: "LAC", heightIn: 74, weightLb: 208, age: 24, jersey: 1 },
  { espnId: "4428331", name: "Rashee Rice", team: "KC", heightIn: 73, weightLb: 204, age: 26, jersey: 4 },
  { espnId: "4032473", name: "Rashid Shaheed", team: "SEA", heightIn: 72, weightLb: 180, age: 27, jersey: 22 },
  { espnId: "4360939", name: "Rashod Bateman", team: "BAL", heightIn: 73, weightLb: 193, age: 26, jersey: 7 },
  { espnId: "4431299", name: "Rome Odunze", team: "CHI", heightIn: 75, weightLb: 214, age: 24, jersey: 15 },
  { espnId: "4361432", name: "Romeo Doubs", team: "NE", heightIn: 74, weightLb: 210, age: 26, jersey: 87 },
  { espnId: "2976212", name: "Stefon Diggs", team: "WAS", heightIn: 72, weightLb: 191, age: 32, jersey: 18 },
  { espnId: "4239993", name: "Tee Higgins", team: "CIN", heightIn: 76, weightLb: 220, age: 27, jersey: 5 },
  { espnId: "3121422", name: "Terry McLaurin", team: "WAS", heightIn: 72, weightLb: 210, age: 30, jersey: 17 },
  { espnId: "4685472", name: "Tetairoa McMillan", team: "CAR", heightIn: 77, weightLb: 212, age: 23, jersey: 4 },
  { espnId: "4428718", name: "Tre Tucker", team: "LV", heightIn: 68, weightLb: 182, age: 25, jersey: 1 },
  { espnId: "4569587", name: "Wan'Dale Robinson", team: "TEN", heightIn: 68, weightLb: 185, age: 25, jersey: 4 },
  { espnId: "4686422", name: "Xavier Hutchinson", team: "HOU", heightIn: 75, weightLb: 210, age: 26, jersey: 19 },
  { espnId: "4683062", name: "Xavier Worthy", team: "KC", heightIn: 71, weightLb: 165, age: 23, jersey: 1 },
  { espnId: "4429615", name: "Zay Flowers", team: "BAL", heightIn: 69, weightLb: 183, age: 25, jersey: 4 },
];
