// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The wide receivers each team lines up, with the ESPN player id their
// headshot is keyed on. Generated rather than typed out because both
// halves of a row go stale on their own schedule: depth charts change
// week to week, and a player id guessed wrong doesn't fail loudly - it
// renders a different person's face under the right name.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type WideReceiver = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
};

export const WIDE_RECEIVERS: WideReceiver[] = [
  { espnId: "4047646", name: "A.J. Brown", team: "NE" },
  { espnId: "4597500", name: "Adonai Mitchell", team: "NYJ" },
  { espnId: "4360078", name: "Alec Pierce", team: "IND" },
  { espnId: "4374302", name: "Amon-Ra St. Brown", team: "DET" },
  { espnId: "4432773", name: "Brian Thomas Jr.", team: "JAX" },
  { espnId: "4871023", name: "Carnell Tate", team: "TEN" },
  { espnId: "4241389", name: "CeeDee Lamb", team: "DAL" },
  { espnId: "3116165", name: "Chris Godwin Jr.", team: "TB" },
  { espnId: "4361370", name: "Chris Olave", team: "NO" },
  { espnId: "4248528", name: "Christian Watson", team: "GB" },
  { espnId: "3128429", name: "Courtland Sutton", team: "DEN" },
  { espnId: "3916945", name: "Darius Slayton", team: "NYG" },
  { espnId: "16800", name: "Davante Adams", team: "LAR" },
  { espnId: "3126486", name: "Deebo Samuel Sr.", team: "SF" },
  { espnId: "4241478", name: "DeVonta Smith", team: "PHI" },
  { espnId: "3915416", name: "DJ Moore", team: "BUF" },
  { espnId: "4047650", name: "DK Metcalf", team: "PIT" },
  { espnId: "4428850", name: "Dontayvion Wicks", team: "PHI" },
  { espnId: "4426502", name: "Drake London", team: "ATL" },
  { espnId: "4567750", name: "Emeka Egbuka", team: "TB" },
  { espnId: "4569618", name: "Garrett Wilson", team: "NYJ" },
  { espnId: "4426354", name: "George Pickens", team: "DAL" },
  { espnId: "4362628", name: "Ja'Marr Chase", team: "CIN" },
  { espnId: "4361409", name: "Jahan Dotson", team: "ATL" },
  { espnId: "4695883", name: "Jalen Coker", team: "CAR" },
  { espnId: "4382466", name: "Jalen Nailor", team: "LV" },
  { espnId: "4249417", name: "Jalen Tolbert", team: "MIA" },
  { espnId: "4426388", name: "Jameson Williams", team: "DET" },
  { espnId: "4430878", name: "Jaxon Smith-Njigba", team: "SEA" },
  { espnId: "4362249", name: "Jayden Reed", team: "GB" },
  { espnId: "4372016", name: "Jaylen Waddle", team: "DEN" },
  { espnId: "4241463", name: "Jerry Jeudy", team: "CLE" },
  { espnId: "4429205", name: "Jordan Addison", team: "MIN" },
  { espnId: "4880281", name: "Jordyn Tyson", team: "NO" },
  { espnId: "4688813", name: "Josh Downs", team: "IND" },
  { espnId: "4262921", name: "Justin Jefferson", team: "MIN" },
  { espnId: "4870653", name: "KC Concepcion", team: "CLE" },
  { espnId: "4373678", name: "Khalil Shakir", team: "BUF" },
  { espnId: "4612826", name: "Ladd McConkey", team: "LAC" },
  { espnId: "4685278", name: "Luther Burden III", team: "CHI" },
  { espnId: "4595348", name: "Malik Nabers", team: "NYG" },
  { espnId: "4569603", name: "Malik Washington", team: "MIA" },
  { espnId: "4432708", name: "Marvin Harrison Jr.", team: "ARI" },
  { espnId: "4035687", name: "Michael Pittman Jr.", team: "PIT" },
  { espnId: "4360761", name: "Michael Wilson", team: "ARI" },
  { espnId: "16737", name: "Mike Evans", team: "SF" },
  { espnId: "4258173", name: "Nico Collins", team: "HOU" },
  { espnId: "4432620", name: "Parker Washington", team: "JAX" },
  { espnId: "4426515", name: "Puka Nacua", team: "LAR" },
  { espnId: "4429025", name: "Quentin Johnston", team: "LAC" },
  { espnId: "4428331", name: "Rashee Rice", team: "KC" },
  { espnId: "4032473", name: "Rashid Shaheed", team: "SEA" },
  { espnId: "4360939", name: "Rashod Bateman", team: "BAL" },
  { espnId: "4431299", name: "Rome Odunze", team: "CHI" },
  { espnId: "4361432", name: "Romeo Doubs", team: "NE" },
  { espnId: "2976212", name: "Stefon Diggs", team: "WAS" },
  { espnId: "4239993", name: "Tee Higgins", team: "CIN" },
  { espnId: "3121422", name: "Terry McLaurin", team: "WAS" },
  { espnId: "4685472", name: "Tetairoa McMillan", team: "CAR" },
  { espnId: "4428718", name: "Tre Tucker", team: "LV" },
  { espnId: "4569587", name: "Wan'Dale Robinson", team: "TEN" },
  { espnId: "4686422", name: "Xavier Hutchinson", team: "HOU" },
  { espnId: "4683062", name: "Xavier Worthy", team: "KC" },
  { espnId: "4429615", name: "Zay Flowers", team: "BAL" },
];
