// Generated by scripts/sync-players.mjs - do not edit by hand.
//
// The wide receivers each team lines up, with the ESPN player id their
// headshot is keyed on. Generated rather than typed out because both
// halves of a row go stale on their own schedule: depth charts change
// week to week, and a player id guessed wrong doesn't fail loudly - it
// renders a different person's face under the right name.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import type { TeamAbbr } from "@/data/teams";

export type WideReceiver = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
  // Where this player sits on their own team's chart: 1 is the starter,
  // 2 the next one down. The rows below are sorted by NAME, so without
  // this the only way to pick "the top two receivers on the Vikings" was
  // to take the first two alphabetically - which is how Justin Jefferson
  // came to be left off a graphic on a live stream.
  depth?: number;
  // Hint columns for the daily player puzzle. Optional because ESPN does
  // not publish all of them for everyone; the puzzle hides a column it
  // has no values for rather than showing a row of "?".
  heightIn?: number;
  weightLb?: number;
  age?: number;
  jersey?: number;
  college?: string;
};

export const WIDE_RECEIVERS: WideReceiver[] = [
  { espnId: "4047646", name: "A.J. Brown", team: "NE", depth: 1, heightIn: 73, weightLb: 226, age: 29, jersey: 1 },
  { espnId: "4597500", name: "Adonai Mitchell", team: "NYJ", depth: 2, heightIn: 74, weightLb: 205, age: 23, jersey: 15 },
  { espnId: "4360078", name: "Alec Pierce", team: "IND", depth: 1, heightIn: 75, weightLb: 211, age: 26, jersey: 14 },
  { espnId: "4374302", name: "Amon-Ra St. Brown", team: "DET", depth: 1, heightIn: 72, weightLb: 202, age: 26, jersey: 14 },
  { espnId: "4368003", name: "Andrei Iosivas", team: "CIN", depth: 3, heightIn: 75, weightLb: 210, age: 26, jersey: 80 },
  { espnId: "4432773", name: "Brian Thomas Jr.", team: "JAX", depth: 1, heightIn: 74, weightLb: 209, age: 23, jersey: 7 },
  { espnId: "4869645", name: "Caleb Douglas", team: "MIA", depth: 3, heightIn: 76, weightLb: 205, age: 22, jersey: 7 },
  { espnId: "3925357", name: "Calvin Ridley", team: "TEN", depth: 3, heightIn: 73, weightLb: 190, age: 31, jersey: 0 },
  { espnId: "4871023", name: "Carnell Tate", team: "TEN", depth: 1, heightIn: 74, weightLb: 192, age: 21, jersey: 14 },
  { espnId: "4241389", name: "CeeDee Lamb", team: "DAL", depth: 1, heightIn: 74, weightLb: 198, age: 27, jersey: 88 },
  { espnId: "3116165", name: "Chris Godwin Jr.", team: "TB", depth: 2, heightIn: 73, weightLb: 209, age: 30, jersey: 14 },
  { espnId: "4361370", name: "Chris Olave", team: "NO", depth: 1, heightIn: 72, weightLb: 187, age: 26, jersey: 12 },
  { espnId: "4248528", name: "Christian Watson", team: "GB", depth: 1, heightIn: 76, weightLb: 215, age: 27, jersey: 9 },
  { espnId: "2977187", name: "Cooper Kupp", team: "SEA", depth: 3, heightIn: 73, weightLb: 205, age: 33, jersey: 10 },
  { espnId: "3128429", name: "Courtland Sutton", team: "DEN", depth: 1, heightIn: 76, weightLb: 216, age: 30, jersey: 14 },
  { espnId: "3916945", name: "Darius Slayton", team: "NYG", depth: 2, heightIn: 73, weightLb: 198, age: 29, jersey: 18 },
  { espnId: "4040655", name: "Darnell Mooney", team: "NYG", depth: 3, heightIn: 71, weightLb: 177, age: 28, jersey: 17 },
  { espnId: "16800", name: "Davante Adams", team: "LAR", depth: 3, heightIn: 73, weightLb: 204, age: 33, jersey: 17 },
  { espnId: "4710714", name: "De'Zhaun Stribling", team: "SF", depth: 3, heightIn: 74, weightLb: 207, age: 23, jersey: 15 },
  { espnId: "3126486", name: "Deebo Samuel Sr.", team: "SF", depth: 2, heightIn: 72, weightLb: 215, age: 30, jersey: 19 },
  { espnId: "4427095", name: "DeMario Douglas", team: "NE", depth: 2, heightIn: 68, weightLb: 185, age: 25, jersey: 3 },
  { espnId: "4832800", name: "Denzel Boston", team: "CLE", depth: 3, heightIn: 76, weightLb: 215, age: 22, jersey: 12 },
  { espnId: "4569559", name: "Devaughn Vele", team: "NO", depth: 3, heightIn: 77, weightLb: 210, age: 28, jersey: 14 },
  { espnId: "4241478", name: "DeVonta Smith", team: "PHI", depth: 1, heightIn: 72, weightLb: 170, age: 27, jersey: 6 },
  { espnId: "3915416", name: "DJ Moore", team: "BUF", depth: 1, heightIn: 72, weightLb: 213, age: 29, jersey: 2 },
  { espnId: "4047650", name: "DK Metcalf", team: "PIT", depth: 1, heightIn: 76, weightLb: 229, age: 28, jersey: 4 },
  { espnId: "4428850", name: "Dontayvion Wicks", team: "PHI", depth: 2, heightIn: 73, weightLb: 206, age: 25, jersey: 13 },
  { espnId: "4426502", name: "Drake London", team: "ATL", depth: 1, heightIn: 76, weightLb: 215, age: 25, jersey: 5 },
  { espnId: "4567750", name: "Emeka Egbuka", team: "TB", depth: 1, heightIn: 73, weightLb: 205, age: 23, jersey: 2 },
  { espnId: "4569618", name: "Garrett Wilson", team: "NYJ", depth: 1, heightIn: 72, weightLb: 183, age: 26, jersey: 5 },
  { espnId: "4426354", name: "George Pickens", team: "DAL", depth: 2, heightIn: 75, weightLb: 200, age: 25, jersey: 3 },
  { espnId: "5123663", name: "Isaac TeSlaa", team: "DET", depth: 3, heightIn: 76, weightLb: 214, age: 24, jersey: 18 },
  { espnId: "4870847", name: "Ja'Kobi Lane", team: "BAL", depth: 3, heightIn: 76, weightLb: 200, age: 22, jersey: 6 },
  { espnId: "4362628", name: "Ja'Marr Chase", team: "CIN", depth: 1, heightIn: 72, weightLb: 205, age: 26, jersey: 1 },
  { espnId: "4603186", name: "Jack Bech", team: "LV", depth: 3, heightIn: 73, weightLb: 214, age: 23, jersey: 18 },
  { espnId: "4361409", name: "Jahan Dotson", team: "ATL", depth: 2, heightIn: 71, weightLb: 184, age: 26, jersey: 4 },
  { espnId: "3916433", name: "Jakobi Meyers", team: "JAX", depth: 3, heightIn: 74, weightLb: 200, age: 29, jersey: 3 },
  { espnId: "4695883", name: "Jalen Coker", team: "CAR", depth: 2, heightIn: 75, weightLb: 213, age: 24, jersey: 18 },
  { espnId: "4430834", name: "Jalen McMillan", team: "TB", depth: 3, heightIn: 73, weightLb: 192, age: 24, jersey: 11 },
  { espnId: "4382466", name: "Jalen Nailor", team: "LV", depth: 2, heightIn: 72, weightLb: 190, age: 27, jersey: 9 },
  { espnId: "4249417", name: "Jalen Tolbert", team: "MIA", depth: 2, heightIn: 73, weightLb: 195, age: 27, jersey: 1 },
  { espnId: "4426388", name: "Jameson Williams", team: "DET", depth: 2, heightIn: 73, weightLb: 184, age: 25, jersey: 1 },
  { espnId: "3886598", name: "Jauan Jennings", team: "MIN", depth: 3, heightIn: 75, weightLb: 212, age: 29, jersey: 14 },
  { espnId: "4430878", name: "Jaxon Smith-Njigba", team: "SEA", depth: 1, heightIn: 72, weightLb: 197, age: 24, jersey: 11 },
  { espnId: "4362249", name: "Jayden Reed", team: "GB", depth: 2, heightIn: 71, weightLb: 187, age: 26, jersey: 11 },
  { espnId: "4372016", name: "Jaylen Waddle", team: "DEN", depth: 2, heightIn: 70, weightLb: 185, age: 27, jersey: 17 },
  { espnId: "4586312", name: "Jaylin Noel", team: "HOU", depth: 1, heightIn: 71, weightLb: 201, age: 23, jersey: 13 },
  { espnId: "4241463", name: "Jerry Jeudy", team: "CLE", depth: 1, heightIn: 73, weightLb: 195, age: 27, jersey: 3 },
  { espnId: "4429205", name: "Jordan Addison", team: "MIN", depth: 2, heightIn: 71, weightLb: 179, age: 24, jersey: 3 },
  { espnId: "4569382", name: "Jordan Whittington", team: "LAR", depth: 1, heightIn: 73, weightLb: 202, age: 25, jersey: 88 },
  { espnId: "4880281", name: "Jordyn Tyson", team: "NO", depth: 2, heightIn: 74, weightLb: 203, age: 22, jersey: 0 },
  { espnId: "4688813", name: "Josh Downs", team: "IND", depth: 2, heightIn: 69, weightLb: 171, age: 25, jersey: 2 },
  { espnId: "4262921", name: "Justin Jefferson", team: "MIN", depth: 1, heightIn: 73, weightLb: 195, age: 27, jersey: 18 },
  { espnId: "2973405", name: "Kalif Raymond", team: "CHI", depth: 1, heightIn: 69, weightLb: 160, age: 32, jersey: 14 },
  { espnId: "4870653", name: "KC Concepcion", team: "CLE", depth: 2, heightIn: 72, weightLb: 190, age: 21, jersey: 1 },
  { espnId: "15818", name: "Keenan Allen", team: "IND", depth: 3, heightIn: 74, weightLb: 211, age: 34, jersey: 10 },
  { espnId: "3045523", name: "Kendrick Bourne", team: "ARI", depth: 3, heightIn: 73, weightLb: 205, age: 31, jersey: 17 },
  { espnId: "4635008", name: "Keon Coleman", team: "BUF", depth: 3, heightIn: 75, weightLb: 213, age: 23, jersey: 0 },
  { espnId: "4373678", name: "Khalil Shakir", team: "BUF", depth: 2, heightIn: 72, weightLb: 190, age: 26, jersey: 10 },
  { espnId: "4612826", name: "Ladd McConkey", team: "LAC", depth: 1, heightIn: 72, weightLb: 185, age: 24, jersey: 15 },
  { espnId: "4426948", name: "Luke McCaffrey", team: "WAS", depth: 1, heightIn: 74, weightLb: 195, age: 25, jersey: 11 },
  { espnId: "4685278", name: "Luther Burden III", team: "CHI", depth: 3, heightIn: 72, weightLb: 210, age: 22, jersey: 10 },
  { espnId: "4870795", name: "Makai Lemon", team: "PHI", depth: 3, heightIn: 71, weightLb: 192, age: 22, jersey: 9 },
  { espnId: "4595348", name: "Malik Nabers", team: "NYG", depth: 1, heightIn: 72, weightLb: 200, age: 23, jersey: 1 },
  { espnId: "4569603", name: "Malik Washington", team: "MIA", depth: 1, heightIn: 68, weightLb: 195, age: 25, jersey: 6 },
  { espnId: "4432708", name: "Marvin Harrison Jr.", team: "ARI", depth: 1, heightIn: 75, weightLb: 220, age: 24, jersey: 18 },
  { espnId: "4701936", name: "Matthew Golden", team: "GB", depth: 3, heightIn: 71, weightLb: 191, age: 23, jersey: 0 },
  { espnId: "4035687", name: "Michael Pittman Jr.", team: "PIT", depth: 2, heightIn: 76, weightLb: 223, age: 28, jersey: 11 },
  { espnId: "4360761", name: "Michael Wilson", team: "ARI", depth: 2, heightIn: 74, weightLb: 213, age: 26, jersey: 14 },
  { espnId: "16737", name: "Mike Evans", team: "SF", depth: 1, heightIn: 77, weightLb: 231, age: 33, jersey: 5 },
  { espnId: "4258173", name: "Nico Collins", team: "HOU", depth: 2, heightIn: 76, weightLb: 222, age: 27, jersey: 12 },
  { espnId: "3917914", name: "Olamide Zaccheaus", team: "ATL", depth: 3, heightIn: 68, weightLb: 194, age: 29, jersey: 14 },
  { espnId: "4723820", name: "Omar Cooper Jr.", team: "NYJ", depth: 3, heightIn: 72, weightLb: 199, age: 22, jersey: 83 },
  { espnId: "4432620", name: "Parker Washington", team: "JAX", depth: 2, heightIn: 70, weightLb: 204, age: 24, jersey: 11 },
  { espnId: "4426515", name: "Puka Nacua", team: "LAR", depth: 2, heightIn: 74, weightLb: 216, age: 25, jersey: 12 },
  { espnId: "4429025", name: "Quentin Johnston", team: "LAC", depth: 2, heightIn: 74, weightLb: 208, age: 24, jersey: 1 },
  { espnId: "4428331", name: "Rashee Rice", team: "KC", depth: 1, heightIn: 73, weightLb: 204, age: 26, jersey: 4 },
  { espnId: "4032473", name: "Rashid Shaheed", team: "SEA", depth: 2, heightIn: 72, weightLb: 180, age: 27, jersey: 22 },
  { espnId: "4360939", name: "Rashod Bateman", team: "BAL", depth: 2, heightIn: 73, weightLb: 193, age: 26, jersey: 7 },
  { espnId: "4431492", name: "Roman Wilson", team: "PIT", depth: 3, heightIn: 70, weightLb: 186, age: 25, jersey: 14 },
  { espnId: "4431299", name: "Rome Odunze", team: "CHI", depth: 2, heightIn: 75, weightLb: 214, age: 24, jersey: 15 },
  { espnId: "4361432", name: "Romeo Doubs", team: "NE", depth: 3, heightIn: 74, weightLb: 210, age: 26, jersey: 87 },
  { espnId: "5083754", name: "Ryan Flournoy", team: "DAL", depth: 3, heightIn: 73, weightLb: 205, age: 26, jersey: 19 },
  { espnId: "2976212", name: "Stefon Diggs", team: "WAS", depth: 3, heightIn: 72, weightLb: 191, age: 32, jersey: 18 },
  { espnId: "4239993", name: "Tee Higgins", team: "CIN", depth: 2, heightIn: 76, weightLb: 220, age: 27, jersey: 5 },
  { espnId: "3121422", name: "Terry McLaurin", team: "WAS", depth: 2, heightIn: 72, weightLb: 210, age: 30, jersey: 17 },
  { espnId: "4685472", name: "Tetairoa McMillan", team: "CAR", depth: 1, heightIn: 77, weightLb: 212, age: 23, jersey: 4 },
  { espnId: "4428718", name: "Tre Tucker", team: "LV", depth: 1, heightIn: 68, weightLb: 182, age: 25, jersey: 1 },
  { espnId: "4686612", name: "Tre' Harris", team: "LAC", depth: 3, heightIn: 75, weightLb: 210, age: 24, jersey: 9 },
  { espnId: "4431280", name: "Troy Franklin", team: "DEN", depth: 3, heightIn: 75, weightLb: 180, age: 23, jersey: 11 },
  { espnId: "4362921", name: "Tyquan Thornton", team: "KC", depth: 3, heightIn: 74, weightLb: 185, age: 26, jersey: 2 },
  { espnId: "4569587", name: "Wan'Dale Robinson", team: "TEN", depth: 2, heightIn: 68, weightLb: 185, age: 25, jersey: 4 },
  { espnId: "4686422", name: "Xavier Hutchinson", team: "HOU", depth: 3, heightIn: 75, weightLb: 210, age: 26, jersey: 19 },
  { espnId: "4430034", name: "Xavier Legette", team: "CAR", depth: 3, heightIn: 75, weightLb: 227, age: 25, jersey: 17 },
  { espnId: "4683062", name: "Xavier Worthy", team: "KC", depth: 2, heightIn: 71, weightLb: 165, age: 23, jersey: 1 },
  { espnId: "4429615", name: "Zay Flowers", team: "BAL", depth: 1, heightIn: 69, weightLb: 183, age: 25, jersey: 4 },
];
