// Writes src/data/qbs.ts from ESPN's own roster data.
//
//   node scripts/sync-qbs.mjs
//
// Exists because the two halves of a quarterback row go stale on
// different schedules and neither fails loudly. Starters change week to
// week. A player id typed in wrong renders a different person's face
// under the right name - which is worse than a broken image, because
// nothing about it looks broken.
//
// So neither half is ever written by hand. This asks ESPN for each
// team's roster, takes the quarterbacks in the order ESPN lists them
// (which is depth-chart order), and keeps the first. Every id in the
// output came from the same response as the name beside it, so the two
// cannot disagree.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "data", "qbs.ts");

// ESPN's team abbreviations differ from ours in one place, the same way
// they do for the logos in teams.ts.
const ESPN_TO_OURS = { WSH: "WAS" };

async function json(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.json();
}

async function main() {
  const teams = (await json("https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams"))
    .sports[0].leagues[0].teams.map((t) => t.team);
  if (teams.length !== 32) throw new Error(`Expected 32 teams, got ${teams.length}`);

  const rows = [];
  const missing = [];
  for (const team of teams) {
    const abbr = (ESPN_TO_OURS[team.abbreviation] ?? team.abbreviation).toUpperCase();
    const roster = await json(
      `https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams/${team.id}/roster`,
    );
    const groups = roster.athletes ?? [];
    const athletes = groups.flatMap((g) => g.items ?? g.athletes ?? [g]).filter(Boolean);
    const qb = athletes.find((a) => (a.position?.abbreviation ?? a.position?.name) === "QB");
    if (!qb) {
      missing.push(abbr);
      continue;
    }
    rows.push({ espnId: String(qb.id), name: qb.fullName ?? qb.displayName, team: abbr });
    process.stdout.write(`${abbr.padEnd(4)} ${String(qb.id).padEnd(9)} ${qb.fullName}\n`);
  }

  // A partial file is worse than none: a category quietly missing five
  // teams looks like a finished list to everyone who didn't run this.
  if (missing.length) throw new Error(`No quarterback found for: ${missing.join(", ")}`);

  rows.sort((a, b) => a.name.localeCompare(b.name));

  const header = `// Generated by scripts/sync-qbs.mjs - do not edit by hand.
//
// One starting quarterback per team, with the ESPN player id its headshot
// is keyed on. Generated rather than typed out because both halves of a
// row go stale on their own schedule: starters change week to week, and a
// player id guessed wrong doesn't fail loudly - it renders a different
// person's face under the right name. Re-run the script whenever the
// depth charts move.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type Quarterback = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
};

export const QUARTERBACKS: Quarterback[] = [
`;
  const body = rows
    .map((r) => `  { espnId: "${r.espnId}", name: ${JSON.stringify(r.name)}, team: "${r.team}" },`)
    .join("\n");
  const footer = `
];

// The headshot ESPN serves for a player id. The "full" cut is a 1040x760
// transparent PNG framed at the shoulders, which is why these are drawn
// cropped to a square rather than fitted inside one - see the portrait
// branch in TierItemChip.
export function espnHeadshot(espnId: string): string {
  return \`https://a.espncdn.com/i/headshots/nfl/players/full/\${espnId}.png\`;
}
`;

  writeFileSync(OUT, header + body + footer);
  console.log(`\nWrote ${rows.length} quarterbacks to src/data/qbs.ts`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
