-- The daily game: guess the mystery player in eight tries.
--
-- Everything that decides anything lives here rather than in the client,
-- and that is the whole reason this file is as big as it is. A puzzle
-- whose answer ships to the browser is not a puzzle - it is a page with
-- the answer in it, and it would be posted in the Discord within the
-- hour. So the client sends a guess and gets back a comparison; it never
-- receives today's player until the round is over.
--
-- Three tables:
--   puzzle_players  the pool, a copy of src/data/puzzlePlayers.ts.
--                   Regenerated by scripts/gen-puzzle-seed.mjs.
--   daily_puzzles   which player each date resolved to, written once.
--   puzzle_guesses  who guessed what, and in what order.
--
-- None of them is client-readable. RLS is on with no policies at all,
-- which is not an oversight: every read goes through the security-definer
-- functions below, and a direct select on daily_puzzles would hand over
-- the answer.

-- ---------------------------------------------------------------------
-- The pool
-- ---------------------------------------------------------------------
create table if not exists public.puzzle_players (
  espn_id text primary key,
  name text not null,
  team text not null,
  position text not null,
  conference text not null,
  division text not null,
  -- Optional: the roster sync did not originally capture these. Every
  -- hint column checks for its own value, so the game plays with four
  -- columns until they are filled in and more afterwards.
  height_in integer,
  weight_lb integer,
  age integer,
  jersey integer,
  college text,
  -- Position in the shuffled running order the daily pick indexes into.
  -- Assigned once, on the way in, and never moved: reshuffling would
  -- change which player "today" is, mid-season, for everyone.
  slot integer unique
);
alter table public.puzzle_players enable row level security;

-- ---------------------------------------------------------------------
-- Which player belongs to which date
-- ---------------------------------------------------------------------
-- Written on the first request of the day and never recomputed. The pick
-- could be derived from the date every time, but then re-seeding the pool
-- at noon would change the answer under everyone who had already played -
-- their correct guesses would retroactively become wrong. Recording it
-- makes the day's answer a fact rather than a calculation.
create table if not exists public.daily_puzzles (
  puzzle_on date primary key,
  espn_id text not null references public.puzzle_players(espn_id)
);
alter table public.daily_puzzles enable row level security;

create table if not exists public.puzzle_guesses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  puzzle_on date not null,
  espn_id text not null references public.puzzle_players(espn_id),
  created_at timestamptz not null default now(),
  -- One shot per player per day. Without this the same wrong guess could
  -- be spent twice, which is free information about nothing.
  unique (user_id, puzzle_on, espn_id)
);
create index if not exists puzzle_guesses_user_day_idx
  on public.puzzle_guesses (user_id, puzzle_on, created_at);
alter table public.puzzle_guesses enable row level security;

-- ---------------------------------------------------------------------
-- Rules, in one place
-- ---------------------------------------------------------------------
create or replace function public.puzzle_max_guesses()
returns integer language sql immutable as $$ select 8 $$;

-- Solved on the first guess is worth 300; every extra guess costs 25, to
-- a floor of 125. Nothing at all for failing, and nothing for playing -
-- see 0043_reprice_economy.sql for what happens when the app pays for
-- turning up rather than for being right.
create or replace function public.puzzle_points(guesses_used integer)
returns integer language sql immutable as $$
  select greatest(125, 300 - 25 * (greatest(guesses_used, 1) - 1));
$$;

-- The day rolls at midnight in New York, like the check-in. One clock for
-- the whole app, and it is the league's.
create or replace function public.puzzle_today()
returns date language sql stable as $$
  select (now() at time zone 'America/New_York')::date;
$$;

-- ---------------------------------------------------------------------
-- Resolving a date to a player
-- ---------------------------------------------------------------------
-- Walks the shuffled order one place per day, so the pool is exhausted
-- before anything repeats - a hash of the date would collide and serve
-- the same player twice in a fortnight. The epoch is arbitrary; it only
-- has to stay put.
create or replace function public.ensure_daily_puzzle(p_on date)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_slot integer;
  v_id text;
begin
  select espn_id into v_id from public.daily_puzzles where puzzle_on = p_on;
  if v_id is not null then
    return v_id;
  end if;

  select count(*) into v_count from public.puzzle_players where slot is not null;
  if v_count = 0 then
    raise exception 'No puzzle players seeded - run scripts/gen-puzzle-seed.mjs and load supabase/seeds/puzzle_players.sql';
  end if;

  v_slot := ((p_on - date '2026-01-01') % v_count + v_count) % v_count + 1;
  select espn_id into v_id from public.puzzle_players where slot = v_slot;

  -- Slots can have gaps if a player was ever deleted; step to the next
  -- one rather than serving nothing.
  if v_id is null then
    select espn_id into v_id
      from public.puzzle_players
     where slot >= v_slot
     order by slot
     limit 1;
  end if;
  if v_id is null then
    select espn_id into v_id from public.puzzle_players where slot is not null order by slot limit 1;
  end if;

  -- Two first-players-of-the-day racing each other both insert; the
  -- primary key decides, and both then read the same winner back.
  insert into public.daily_puzzles (puzzle_on, espn_id)
  values (p_on, v_id)
  on conflict (puzzle_on) do nothing;

  select espn_id into v_id from public.daily_puzzles where puzzle_on = p_on;
  return v_id;
end;
$$;

-- ---------------------------------------------------------------------
-- Comparing a guess to the answer
-- ---------------------------------------------------------------------
-- One row of the board. Numeric columns report a direction as well as a
-- verdict, because "older" is the hint - "wrong" is not.
--
-- A null on either side reports 'unknown' rather than 'miss': until the
-- roster sync fills in height and weight, saying "miss" would be a lie
-- the player could act on.
create or replace function public.puzzle_compare(p_guess text, p_answer text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  g public.puzzle_players%rowtype;
  a public.puzzle_players%rowtype;
  function_result jsonb;
begin
  select * into g from public.puzzle_players where espn_id = p_guess;
  select * into a from public.puzzle_players where espn_id = p_answer;
  if g.espn_id is null or a.espn_id is null then
    raise exception 'Unknown player';
  end if;

  function_result := jsonb_build_object(
    'espnId', g.espn_id,
    'name', g.name,
    'correct', g.espn_id = a.espn_id,
    'team', jsonb_build_object('value', g.team, 'status', case when g.team = a.team then 'hit' else 'miss' end),
    'conference', jsonb_build_object(
      'value', g.conference,
      'status', case when g.conference = a.conference then 'hit' else 'miss' end
    ),
    -- Division is compared as the whole thing, not the word: "East" in
    -- the NFC tells you nothing about "East" in the AFC, and colouring
    -- those green would be actively misleading.
    'division', jsonb_build_object(
      'value', g.conference || ' ' || g.division,
      'status', case when g.conference = a.conference and g.division = a.division then 'hit' else 'miss' end
    ),
    'position', jsonb_build_object('value', g.position, 'status', case when g.position = a.position then 'hit' else 'miss' end)
  );

  function_result := function_result
    || public.puzzle_num('height', g.height_in, a.height_in, 2)
    || public.puzzle_num('weight', g.weight_lb, a.weight_lb, 15)
    || public.puzzle_num('age', g.age, a.age, 2)
    || public.puzzle_num('jersey', g.jersey, a.jersey, 5)
    || jsonb_build_object('college', jsonb_build_object(
         'value', g.college,
         'status', case
           when g.college is null or a.college is null then 'unknown'
           when g.college = a.college then 'hit'
           else 'miss'
         end,
         'direction', null
       ));

  return function_result;
end;
$$;

-- One numeric column: exact, within a band, or wrong - plus which way to
-- go. Pulled out so the four of them cannot drift apart.
create or replace function public.puzzle_num(p_key text, p_guess integer, p_answer integer, p_band integer)
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(p_key, jsonb_build_object(
    'value', p_guess,
    'status', case
      when p_guess is null or p_answer is null then 'unknown'
      when p_guess = p_answer then 'hit'
      when abs(p_guess - p_answer) <= p_band then 'close'
      else 'miss'
    end,
    'direction', case
      when p_guess is null or p_answer is null or p_guess = p_answer then null
      when p_guess < p_answer then 'up'
      else 'down'
    end
  ));
$$;

-- ---------------------------------------------------------------------
-- The whole board, as the client should see it
-- ---------------------------------------------------------------------
-- Everything the UI needs and nothing it should not have. The answer is
-- attached only once the round is over - solved, or out of guesses.
create or replace function public.daily_puzzle_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_on date := public.puzzle_today();
  v_answer text;
  v_max integer := public.puzzle_max_guesses();
  v_rows jsonb;
  v_used integer;
  v_solved boolean;
  v_finished boolean;
begin
  if v_uid is null then
    raise exception 'Not signed in';
  end if;

  v_answer := public.ensure_daily_puzzle(v_on);

  select coalesce(jsonb_agg(public.puzzle_compare(pg.espn_id, v_answer) order by pg.created_at), '[]'::jsonb),
         count(*)
    into v_rows, v_used
    from public.puzzle_guesses pg
   where pg.user_id = v_uid and pg.puzzle_on = v_on;

  v_solved := exists (
    select 1 from public.puzzle_guesses
     where user_id = v_uid and puzzle_on = v_on and espn_id = v_answer
  );
  v_finished := v_solved or v_used >= v_max;

  return jsonb_build_object(
    'puzzleOn', v_on,
    'maxGuesses', v_max,
    'guessesUsed', v_used,
    'guesses', v_rows,
    'solved', v_solved,
    'finished', v_finished,
    'pointsAwarded', case when v_solved then public.puzzle_points(v_used) else 0 end,
    'answer', case
      when v_finished then (
        select jsonb_build_object('espnId', espn_id, 'name', name, 'team', team, 'position', position)
          from public.puzzle_players where espn_id = v_answer
      )
      else null
    end
  );
end;
$$;

-- ---------------------------------------------------------------------
-- Playing a guess
-- ---------------------------------------------------------------------
-- Returns the same shape as daily_puzzle_state so the client can simply
-- replace what it is holding rather than merging a delta into it.
create or replace function public.submit_daily_guess(p_espn_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_on date := public.puzzle_today();
  v_answer text;
  v_used integer;
  v_max integer := public.puzzle_max_guesses();
begin
  if v_uid is null then
    raise exception 'Not signed in';
  end if;

  v_answer := public.ensure_daily_puzzle(v_on);

  if not exists (select 1 from public.puzzle_players where espn_id = p_espn_id) then
    raise exception 'Not a player in the pool';
  end if;

  -- Lock this player's row for the day before counting, so two guesses
  -- fired at once cannot both see "7 used" and take the total to 9.
  perform 1 from public.daily_puzzles where puzzle_on = v_on for update;

  select count(*) into v_used
    from public.puzzle_guesses
   where user_id = v_uid and puzzle_on = v_on;

  if exists (
    select 1 from public.puzzle_guesses
     where user_id = v_uid and puzzle_on = v_on and espn_id = v_answer
  ) then
    raise exception 'Already solved today';
  end if;
  if v_used >= v_max then
    raise exception 'No guesses left today';
  end if;
  -- Said out loud rather than left to the unique index below. The index
  -- absorbs a repeat with on conflict do nothing, which is safe - no
  -- guess is spent - but from the outside it is a button that does
  -- nothing and says nothing. The client greys out names already played;
  -- this is what it gets if that ever fails to hold.
  if exists (
    select 1 from public.puzzle_guesses
     where user_id = v_uid and puzzle_on = v_on and espn_id = p_espn_id
  ) then
    raise exception 'You already guessed that player today';
  end if;

  insert into public.puzzle_guesses (user_id, puzzle_on, espn_id)
  values (v_uid, v_on, p_espn_id)
  on conflict (user_id, puzzle_on, espn_id) do nothing;

  -- Points land here rather than in a sync_ function because this is the
  -- only moment that knows how many guesses it took. reference_id is the
  -- date, so the unique index makes a second payout impossible.
  if p_espn_id = v_answer then
    insert into public.point_events (user_id, source, points, reference_id)
    values (v_uid, 'daily_puzzle', public.puzzle_points(v_used + 1), v_on::text)
    on conflict (user_id, source, reference_id) do nothing;
  end if;

  return public.daily_puzzle_state();
end;
$$;

revoke all on function public.ensure_daily_puzzle(date) from public;
revoke all on function public.puzzle_compare(text, text) from public;
revoke all on function public.daily_puzzle_state() from public;
revoke all on function public.submit_daily_guess(text) from public;
grant execute on function public.daily_puzzle_state() to authenticated;
grant execute on function public.submit_daily_guess(text) to authenticated;
