-- Picks lock when the game kicks off.
--
-- GENERATED by scripts/gen-kickoff-migration.mjs from src/data/games.ts.
-- Do not edit by hand - regenerate and re-run. Idempotent end to end, so
-- running it again after a schedule change is the update.
--
-- What this replaces: until now the only thing that closed picking was
-- weeks.is_open, a boolean somebody flips in the admin panel. That is a
-- chore, not a deadline, and the first Wednesday night of the season is
-- what it cost - the game kicked off at 8:20 ET, the flag never got
-- flipped, and every account could still change its pick on a game that
-- had already been played.
--
-- Per game, not per week. Closing the whole slate at the week's first
-- kickoff would freeze Sunday's fifteen games on Wednesday night.
-- weeks.is_open stays on top of this as a manual override; it is just no
-- longer the only thing standing between a played game and an edit.

-- The database's own copy of the kickoff times. Readable by anyone (they
-- are printed on the board already), writable by admins only - a user who
-- could edit this table could move a kickoff into the future and reopen a
-- game they had just watched.
create table if not exists public.game_kickoffs (
  game_id text primary key,
  week integer not null,
  kickoff timestamptz not null
);
create index if not exists game_kickoffs_week_idx on public.game_kickoffs (week);
alter table public.game_kickoffs enable row level security;

drop policy if exists "game_kickoffs_select_all" on public.game_kickoffs;
create policy "game_kickoffs_select_all" on public.game_kickoffs for select using (true);
drop policy if exists "game_kickoffs_insert_admin" on public.game_kickoffs;
create policy "game_kickoffs_insert_admin" on public.game_kickoffs for insert with check (public.is_admin());
drop policy if exists "game_kickoffs_update_admin" on public.game_kickoffs;
create policy "game_kickoffs_update_admin" on public.game_kickoffs for update using (public.is_admin());
drop policy if exists "game_kickoffs_delete_admin" on public.game_kickoffs;
create policy "game_kickoffs_delete_admin" on public.game_kickoffs for delete using (public.is_admin());

-- The schedule, 272 games, straight from src/data/games.ts.
insert into public.game_kickoffs (game_id, week, kickoff) values
  ('2026-w1-ne-sea', 1, '2026-09-09T20:20:00-04:00'::timestamptz),
  ('2026-w1-lar-sf', 1, '2026-09-10T20:35:00-04:00'::timestamptz),
  ('2026-w1-tb-cin', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-no-det', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-nyj-ten', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-bal-ind', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-atl-pit', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-chi-car', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-cle-jax', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-buf-hou', 1, '2026-09-13T13:00:00-04:00'::timestamptz),
  ('2026-w1-mia-lv', 1, '2026-09-13T16:25:00-04:00'::timestamptz),
  ('2026-w1-gb-min', 1, '2026-09-13T16:25:00-04:00'::timestamptz),
  ('2026-w1-was-phi', 1, '2026-09-13T16:25:00-04:00'::timestamptz),
  ('2026-w1-ari-lac', 1, '2026-09-13T16:25:00-04:00'::timestamptz),
  ('2026-w1-dal-nyg', 1, '2026-09-13T20:20:00-04:00'::timestamptz),
  ('2026-w1-den-kc', 1, '2026-09-14T20:15:00-04:00'::timestamptz),
  ('2026-w2-det-buf', 2, '2026-09-17T20:15:00-04:00'::timestamptz),
  ('2026-w2-car-atl', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-no-bal', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-min-chi', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-cin-hou', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-pit-ne', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-gb-nyj', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-cle-tb', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-phi-ten', 2, '2026-09-20T13:00:00-04:00'::timestamptz),
  ('2026-w2-jax-den', 2, '2026-09-20T16:05:00-04:00'::timestamptz),
  ('2026-w2-lv-lac', 2, '2026-09-20T16:05:00-04:00'::timestamptz),
  ('2026-w2-sea-ari', 2, '2026-09-20T16:25:00-04:00'::timestamptz),
  ('2026-w2-was-dal', 2, '2026-09-20T16:25:00-04:00'::timestamptz),
  ('2026-w2-mia-sf', 2, '2026-09-20T16:25:00-04:00'::timestamptz),
  ('2026-w2-ind-kc', 2, '2026-09-20T20:20:00-04:00'::timestamptz),
  ('2026-w2-nyg-lar', 2, '2026-09-21T20:15:00-04:00'::timestamptz),
  ('2026-w3-atl-gb', 3, '2026-09-24T20:15:00-04:00'::timestamptz),
  ('2026-w3-lac-buf', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-car-cle', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-nyj-det', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-hou-ind', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-ne-jax', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-kc-mia', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-ten-nyg', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-cin-pit', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-sea-was', 3, '2026-09-27T13:00:00-04:00'::timestamptz),
  ('2026-w3-ari-sf', 3, '2026-09-27T16:05:00-04:00'::timestamptz),
  ('2026-w3-min-tb', 3, '2026-09-27T16:05:00-04:00'::timestamptz),
  ('2026-w3-lv-no', 3, '2026-09-27T16:25:00-04:00'::timestamptz),
  ('2026-w3-bal-dal', 3, '2026-09-27T16:25:00-04:00'::timestamptz),
  ('2026-w3-lar-den', 3, '2026-09-27T20:20:00-04:00'::timestamptz),
  ('2026-w3-phi-chi', 3, '2026-09-28T20:15:00-04:00'::timestamptz),
  ('2026-w4-pit-cle', 4, '2026-10-01T20:15:00-04:00'::timestamptz),
  ('2026-w4-ind-was', 4, '2026-10-04T09:30:00-04:00'::timestamptz),
  ('2026-w4-ten-bal', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-ne-buf', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-nyj-chi', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-jax-cin', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-dal-hou', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-ari-nyg', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-lar-phi', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-gb-tb', 4, '2026-10-04T13:00:00-04:00'::timestamptz),
  ('2026-w4-mia-min', 4, '2026-10-04T16:05:00-04:00'::timestamptz),
  ('2026-w4-kc-lv', 4, '2026-10-04T16:25:00-04:00'::timestamptz),
  ('2026-w4-lac-sea', 4, '2026-10-04T16:25:00-04:00'::timestamptz),
  ('2026-w4-den-sf', 4, '2026-10-04T16:25:00-04:00'::timestamptz),
  ('2026-w4-det-car', 4, '2026-10-04T20:20:00-04:00'::timestamptz),
  ('2026-w4-atl-no', 4, '2026-10-05T20:15:00-04:00'::timestamptz),
  ('2026-w5-tb-dal', 5, '2026-10-08T20:15:00-04:00'::timestamptz),
  ('2026-w5-phi-jax', 5, '2026-10-11T09:30:00-04:00'::timestamptz),
  ('2026-w5-cin-mia', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-lv-ne', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-min-no', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-cle-nyj', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-ind-pit', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-hou-ten', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-nyg-was', 5, '2026-10-11T13:00:00-04:00'::timestamptz),
  ('2026-w5-den-lac', 5, '2026-10-11T16:05:00-04:00'::timestamptz),
  ('2026-w5-det-ari', 5, '2026-10-11T16:25:00-04:00'::timestamptz),
  ('2026-w5-chi-gb', 5, '2026-10-11T16:25:00-04:00'::timestamptz),
  ('2026-w5-sf-sea', 5, '2026-10-11T16:25:00-04:00'::timestamptz),
  ('2026-w5-bal-atl', 5, '2026-10-11T20:20:00-04:00'::timestamptz),
  ('2026-w5-buf-lar', 5, '2026-10-12T20:15:00-04:00'::timestamptz),
  ('2026-w6-sea-den', 6, '2026-10-15T20:15:00-04:00'::timestamptz),
  ('2026-w6-hou-jax', 6, '2026-10-18T09:30:00-04:00'::timestamptz),
  ('2026-w6-chi-atl', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-bal-cle', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-ten-ind', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-nyj-ne', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-no-nyg', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-car-phi', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-pit-tb', 6, '2026-10-18T13:00:00-04:00'::timestamptz),
  ('2026-w6-ari-lar', 6, '2026-10-18T16:05:00-04:00'::timestamptz),
  ('2026-w6-lac-kc', 6, '2026-10-18T16:25:00-04:00'::timestamptz),
  ('2026-w6-buf-lv', 6, '2026-10-18T16:25:00-04:00'::timestamptz),
  ('2026-w6-dal-gb', 6, '2026-10-18T20:20:00-04:00'::timestamptz),
  ('2026-w6-was-sf', 6, '2026-10-19T20:15:00-04:00'::timestamptz),
  ('2026-w7-ne-chi', 7, '2026-10-22T20:15:00-04:00'::timestamptz),
  ('2026-w7-pit-no', 7, '2026-10-25T09:30:00-04:00'::timestamptz),
  ('2026-w7-sf-atl', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-cin-bal', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-tb-car', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-nyg-hou', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-ind-min', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-mia-nyj', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-cle-ten', 7, '2026-10-25T13:00:00-04:00'::timestamptz),
  ('2026-w7-den-ari', 7, '2026-10-25T16:05:00-04:00'::timestamptz),
  ('2026-w7-gb-det', 7, '2026-10-25T16:25:00-04:00'::timestamptz),
  ('2026-w7-lar-lv', 7, '2026-10-25T16:25:00-04:00'::timestamptz),
  ('2026-w7-kc-sea', 7, '2026-10-25T20:20:00-04:00'::timestamptz),
  ('2026-w7-dal-phi', 7, '2026-10-26T20:15:00-04:00'::timestamptz),
  ('2026-w8-car-gb', 8, '2026-10-29T20:15:00-04:00'::timestamptz),
  ('2026-w8-bal-buf', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-ten-cin', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-ari-dal', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-min-det', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-ind-jax', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-lv-nyj', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-cle-pit', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-atl-tb', 8, '2026-11-01T13:00:00-05:00'::timestamptz),
  ('2026-w8-lac-lar', 8, '2026-11-01T16:05:00-05:00'::timestamptz),
  ('2026-w8-kc-den', 8, '2026-11-01T16:25:00-05:00'::timestamptz),
  ('2026-w8-ne-mia', 8, '2026-11-01T16:25:00-05:00'::timestamptz),
  ('2026-w8-phi-was', 8, '2026-11-01T20:20:00-05:00'::timestamptz),
  ('2026-w8-chi-sea', 8, '2026-11-02T20:15:00-05:00'::timestamptz),
  ('2026-w9-jax-bal', 9, '2026-11-05T20:15:00-05:00'::timestamptz),
  ('2026-w9-cin-atl', 9, '2026-11-08T09:30:00-05:00'::timestamptz),
  ('2026-w9-den-car', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-dal-ind', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-nyj-kc', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-det-mia', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-cle-no', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-nyg-phi', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-lar-was', 9, '2026-11-08T13:00:00-05:00'::timestamptz),
  ('2026-w9-hou-lac', 9, '2026-11-08T16:05:00-05:00'::timestamptz),
  ('2026-w9-lv-sf', 9, '2026-11-08T16:05:00-05:00'::timestamptz),
  ('2026-w9-gb-ne', 9, '2026-11-08T16:25:00-05:00'::timestamptz),
  ('2026-w9-ari-sea', 9, '2026-11-08T16:25:00-05:00'::timestamptz),
  ('2026-w9-tb-chi', 9, '2026-11-08T20:20:00-05:00'::timestamptz),
  ('2026-w9-buf-min', 9, '2026-11-09T20:15:00-05:00'::timestamptz),
  ('2026-w10-was-nyg', 10, '2026-11-12T20:15:00-05:00'::timestamptz),
  ('2026-w10-ne-det', 10, '2026-11-15T09:30:00-05:00'::timestamptz),
  ('2026-w10-kc-atl', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-hou-cle', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-min-gb', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-mia-ind', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-car-no', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-buf-nyj', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-jax-ten', 10, '2026-11-15T13:00:00-05:00'::timestamptz),
  ('2026-w10-lar-ari', 10, '2026-11-15T16:05:00-05:00'::timestamptz),
  ('2026-w10-sea-lv', 10, '2026-11-15T16:05:00-05:00'::timestamptz),
  ('2026-w10-sf-dal', 10, '2026-11-15T16:25:00-05:00'::timestamptz),
  ('2026-w10-pit-cin', 10, '2026-11-15T20:20:00-05:00'::timestamptz),
  ('2026-w10-lac-bal', 10, '2026-11-16T20:15:00-05:00'::timestamptz),
  ('2026-w11-ind-hou', 11, '2026-11-19T20:15:00-05:00'::timestamptz),
  ('2026-w11-mia-buf', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-bal-car', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-no-chi', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-ten-dal', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-tb-det', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-ari-kc', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-jax-nyg', 11, '2026-11-22T13:00:00-05:00'::timestamptz),
  ('2026-w11-nyj-lac', 11, '2026-11-22T16:05:00-05:00'::timestamptz),
  ('2026-w11-lv-den', 11, '2026-11-22T16:25:00-05:00'::timestamptz),
  ('2026-w11-pit-phi', 11, '2026-11-22T16:25:00-05:00'::timestamptz),
  ('2026-w11-min-sf', 11, '2026-11-22T20:20:00-05:00'::timestamptz),
  ('2026-w11-cin-was', 11, '2026-11-23T20:15:00-05:00'::timestamptz),
  ('2026-w12-gb-lar', 12, '2026-11-25T20:00:00-05:00'::timestamptz),
  ('2026-w12-chi-det', 12, '2026-11-26T13:00:00-05:00'::timestamptz),
  ('2026-w12-phi-dal', 12, '2026-11-26T16:30:00-05:00'::timestamptz),
  ('2026-w12-kc-buf', 12, '2026-11-26T20:20:00-05:00'::timestamptz),
  ('2026-w12-den-pit', 12, '2026-11-27T15:00:00-05:00'::timestamptz),
  ('2026-w12-no-cin', 12, '2026-11-29T13:00:00-05:00'::timestamptz),
  ('2026-w12-lv-cle', 12, '2026-11-29T13:00:00-05:00'::timestamptz),
  ('2026-w12-bal-hou', 12, '2026-11-29T13:00:00-05:00'::timestamptz),
  ('2026-w12-nyg-ind', 12, '2026-11-29T13:00:00-05:00'::timestamptz),
  ('2026-w12-nyj-mia', 12, '2026-11-29T13:00:00-05:00'::timestamptz),
  ('2026-w12-atl-min', 12, '2026-11-29T13:00:00-05:00'::timestamptz),
  ('2026-w12-ten-jax', 12, '2026-11-29T16:05:00-05:00'::timestamptz),
  ('2026-w12-was-ari', 12, '2026-11-29T16:25:00-05:00'::timestamptz),
  ('2026-w12-sea-sf', 12, '2026-11-29T16:25:00-05:00'::timestamptz),
  ('2026-w12-ne-lac', 12, '2026-11-29T20:20:00-05:00'::timestamptz),
  ('2026-w12-car-tb', 12, '2026-11-30T20:15:00-05:00'::timestamptz),
  ('2026-w13-kc-lar', 13, '2026-12-03T20:15:00-05:00'::timestamptz),
  ('2026-w13-det-atl', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-jax-chi', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-cin-cle', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-gb-no', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-sf-nyg', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-lac-tb', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-was-ten', 13, '2026-12-06T13:00:00-05:00'::timestamptz),
  ('2026-w13-phi-ari', 13, '2026-12-06T16:05:00-05:00'::timestamptz),
  ('2026-w13-mia-den', 13, '2026-12-06T16:05:00-05:00'::timestamptz),
  ('2026-w13-car-min', 13, '2026-12-06T16:25:00-05:00'::timestamptz),
  ('2026-w13-buf-ne', 13, '2026-12-06T16:25:00-05:00'::timestamptz),
  ('2026-w13-hou-pit', 13, '2026-12-06T20:20:00-05:00'::timestamptz),
  ('2026-w13-dal-sea', 13, '2026-12-07T20:15:00-05:00'::timestamptz),
  ('2026-w14-min-ne', 14, '2026-12-10T20:15:00-05:00'::timestamptz),
  ('2026-w14-tb-bal', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-no-car', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-atl-cle', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-ten-det', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-chi-mia', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-den-nyj', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-ind-phi', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-hou-was', 14, '2026-12-13T13:00:00-05:00'::timestamptz),
  ('2026-w14-lac-lv', 14, '2026-12-13T16:05:00-05:00'::timestamptz),
  ('2026-w14-kc-cin', 14, '2026-12-13T16:25:00-05:00'::timestamptz),
  ('2026-w14-nyg-sea', 14, '2026-12-13T16:25:00-05:00'::timestamptz),
  ('2026-w14-lar-sf', 14, '2026-12-13T16:25:00-05:00'::timestamptz),
  ('2026-w14-buf-gb', 14, '2026-12-13T20:20:00-05:00'::timestamptz),
  ('2026-w14-pit-jax', 14, '2026-12-14T20:15:00-05:00'::timestamptz),
  ('2026-w15-sf-lac', 15, '2026-12-17T20:15:00-05:00'::timestamptz),
  ('2026-w15-sea-phi', 15, '2026-12-19T17:00:00-05:00'::timestamptz),
  ('2026-w15-chi-buf', 15, '2026-12-19T20:20:00-05:00'::timestamptz),
  ('2026-w15-cin-car', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-mia-gb', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-jax-hou', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-cle-nyg', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-bal-pit', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-no-tb', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-ind-ten', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-atl-was', 15, '2026-12-20T13:00:00-05:00'::timestamptz),
  ('2026-w15-nyj-ari', 15, '2026-12-20T16:05:00-05:00'::timestamptz),
  ('2026-w15-dal-lar', 15, '2026-12-20T16:25:00-05:00'::timestamptz),
  ('2026-w15-den-lv', 15, '2026-12-20T16:25:00-05:00'::timestamptz),
  ('2026-w15-det-min', 15, '2026-12-20T20:20:00-05:00'::timestamptz),
  ('2026-w15-ne-kc', 15, '2026-12-21T20:15:00-05:00'::timestamptz),
  ('2026-w16-hou-phi', 16, '2026-12-24T20:15:00-05:00'::timestamptz),
  ('2026-w16-gb-chi', 16, '2026-12-25T13:00:00-05:00'::timestamptz),
  ('2026-w16-buf-den', 16, '2026-12-25T16:30:00-05:00'::timestamptz),
  ('2026-w16-lar-sea', 16, '2026-12-25T20:15:00-05:00'::timestamptz),
  ('2026-w16-cle-bal', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-lac-mia', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-ari-no', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-ne-nyj', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-ten-lv', 16, '2026-12-27T16:05:00-05:00'::timestamptz),
  ('2026-w16-sf-kc', 16, '2026-12-27T16:25:00-05:00'::timestamptz),
  ('2026-w16-jax-dal', 16, '2026-12-27T20:20:00-05:00'::timestamptz),
  ('2026-w16-nyg-det', 16, '2026-12-28T20:15:00-05:00'::timestamptz),
  ('2026-w16-tb-atl', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-cin-ind', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-was-min', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w16-car-pit', 16, '2026-12-27T13:00:00-05:00'::timestamptz),
  ('2026-w17-bal-cin', 17, '2026-12-31T20:15:00-05:00'::timestamptz),
  ('2026-w17-no-atl', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-sea-car', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-ind-cle', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-nyg-dal', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-buf-mia', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-min-nyj', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-pit-ten', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-lv-ari', 17, '2027-01-03T16:05:00-05:00'::timestamptz),
  ('2026-w17-det-chi', 17, '2027-01-03T16:25:00-05:00'::timestamptz),
  ('2026-w17-phi-sf', 17, '2027-01-03T20:20:00-05:00'::timestamptz),
  ('2026-w17-hou-gb', 17, '2027-01-04T20:15:00-05:00'::timestamptz),
  ('2026-w17-was-jax', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-kc-lac', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-den-ne', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w17-lar-tb', 17, '2027-01-03T13:00:00-05:00'::timestamptz),
  ('2026-w18-sf-ari', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-pit-bal', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-nyj-buf', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-atl-car', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-cle-cin', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-lac-den', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-det-gb', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-ten-hou', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-jax-ind', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-lv-kc', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-sea-lar', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-chi-min', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-mia-ne', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-tb-no', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-phi-nyg', 18, '2027-01-10T13:00:00-05:00'::timestamptz),
  ('2026-w18-dal-was', 18, '2027-01-10T13:00:00-05:00'::timestamptz)
on conflict (game_id) do update
  set week = excluded.week,
      kickoff = excluded.kickoff;

-- The rule itself.
--
-- Written as "there IS a row and it is in the future", not "there is NO
-- row saying it started". The difference is what happens to a game_id the
-- table has never heard of: this way it cannot be picked at all, which is
-- loud, obvious and one paste away from fixed. The other way it would be
-- freely editable forever, which is silent, and is the exact bug this
-- migration exists to close. Fail shut.
create or replace function public.game_is_open(p_game_id text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.game_kickoffs k
    where k.game_id = p_game_id and k.kickoff > now()
  );
$$;

drop policy if exists "weekly_picks_insert_own" on public.weekly_picks;
create policy "weekly_picks_insert_own" on public.weekly_picks for insert
  with check (
    auth.uid() = user_id
    and exists (select 1 from public.weeks w where w.week = weekly_picks.week and w.is_open = true)
    and public.game_is_open(weekly_picks.game_id)
  );

drop policy if exists "weekly_picks_update_own" on public.weekly_picks;
create policy "weekly_picks_update_own" on public.weekly_picks for update
  using (
    auth.uid() = user_id
    and exists (select 1 from public.weeks w where w.week = weekly_picks.week and w.is_open = true)
    and public.game_is_open(weekly_picks.game_id)
  );

drop policy if exists "weekly_picks_delete_own" on public.weekly_picks;
create policy "weekly_picks_delete_own" on public.weekly_picks for delete
  using (
    auth.uid() = user_id
    and exists (select 1 from public.weeks w where w.week = weekly_picks.week and w.is_open = true)
    and public.game_is_open(weekly_picks.game_id)
  );
