// Generated by scripts/sync-qbs.mjs - do not edit by hand.
//
// One starting quarterback per team, with the ESPN player id its headshot
// is keyed on. Generated rather than typed out because both halves of a
// row go stale on their own schedule: starters change week to week, and a
// player id guessed wrong doesn't fail loudly - it renders a different
// person's face under the right name. Re-run the script whenever the
// depth charts move.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type Quarterback = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
};

export const QUARTERBACKS: Quarterback[] = [];

// The headshot ESPN serves for a player id. The "full" cut is a 1040x760
// transparent PNG framed at the shoulders, which is why these are drawn
// cropped to a square rather than fitted inside one - see the portrait
// branch in TierItemChip.
export function espnHeadshot(espnId: string): string {
  return `https://a.espncdn.com/i/headshots/nfl/players/full/${espnId}.png`;
}
