// Generated by scripts/sync-qbs.mjs - do not edit by hand.
//
// The starting quarterback per team, with the ESPN player id its headshot
// is keyed on. Generated rather than typed out because both halves of a
// row go stale on their own schedule: starters change week to week, and a
// player id guessed wrong doesn't fail loudly - it renders a different
// person's face under the right name. Re-run the script whenever the
// depth charts move.
//
// Empty until the script has been run once. The tier list category is
// registered off the length of this array (see tierTemplates.ts), so an
// unsynced checkout simply doesn't offer the category rather than
// offering one full of blanks.
import { TeamAbbr } from "@/data/teams";

export type Quarterback = {
  // ESPN's player id, which is also what its headshot URL is keyed on.
  espnId: string;
  name: string;
  team: TeamAbbr;
};

export const QUARTERBACKS: Quarterback[] = [
  { espnId: "8439", name: "Aaron Rodgers", team: "PIT" },
  { espnId: "3052587", name: "Baker Mayfield", team: "TB" },
  { espnId: "4426338", name: "Bo Nix", team: "DEN" },
  { espnId: "4361741", name: "Brock Purdy", team: "SF" },
  { espnId: "4685720", name: "Bryce Young", team: "CAR" },
  { espnId: "4432577", name: "C.J. Stroud", team: "HOU" },
  { espnId: "4431611", name: "Caleb Williams", team: "CHI" },
  { espnId: "4688380", name: "Cam Ward", team: "TEN" },
  { espnId: "2577417", name: "Dak Prescott", team: "DAL" },
  { espnId: "3917792", name: "Daniel Jones", team: "IND" },
  { espnId: "3122840", name: "Deshaun Watson", team: "CLE" },
  { espnId: "4431452", name: "Drake Maye", team: "NE" },
  { espnId: "15864", name: "Geno Smith", team: "NYJ" },
  { espnId: "2578570", name: "Jacoby Brissett", team: "ARI" },
  { espnId: "4040715", name: "Jalen Hurts", team: "PHI" },
  { espnId: "3046779", name: "Jared Goff", team: "DET" },
  { espnId: "4689114", name: "Jaxson Dart", team: "NYG" },
  { espnId: "4426348", name: "Jayden Daniels", team: "WAS" },
  { espnId: "3915511", name: "Joe Burrow", team: "CIN" },
  { espnId: "4036378", name: "Jordan Love", team: "GB" },
  { espnId: "3918298", name: "Josh Allen", team: "BUF" },
  { espnId: "4038941", name: "Justin Herbert", team: "LAC" },
  { espnId: "14880", name: "Kirk Cousins", team: "LV" },
  { espnId: "3917315", name: "Kyler Murray", team: "MIN" },
  { espnId: "3916387", name: "Lamar Jackson", team: "BAL" },
  { espnId: "4242512", name: "Malik Willis", team: "MIA" },
  { espnId: "12483", name: "Matthew Stafford", team: "LAR" },
  { espnId: "3139477", name: "Patrick Mahomes", team: "KC" },
  { espnId: "3912547", name: "Sam Darnold", team: "SEA" },
  { espnId: "4360310", name: "Trevor Lawrence", team: "JAX" },
  { espnId: "4241479", name: "Tua Tagovailoa", team: "ATL" },
  { espnId: "4360689", name: "Tyler Shough", team: "NO" },
];

